# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import water_quality_message_pb2 as water__quality__message__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in water_quality_message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WaterQualityEdgeServiceStub(object):
    """============================================================
    gRPC Service Definition
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAnalysisResults = channel.stream_stream(
                '/com.waterquality.proto.WaterQualityEdgeService/StreamAnalysisResults',
                request_serializer=water__quality__message__pb2.WaterQualityMessage.SerializeToString,
                response_deserializer=water__quality__message__pb2.EdgeCommand.FromString,
                _registered_method=True)
        self.ReportAlert = channel.unary_unary(
                '/com.waterquality.proto.WaterQualityEdgeService/ReportAlert',
                request_serializer=water__quality__message__pb2.AlertRequest.SerializeToString,
                response_deserializer=water__quality__message__pb2.AlertResponse.FromString,
                _registered_method=True)
        self.GetModelVersion = channel.unary_unary(
                '/com.waterquality.proto.WaterQualityEdgeService/GetModelVersion',
                request_serializer=water__quality__message__pb2.ModelVersionRequest.SerializeToString,
                response_deserializer=water__quality__message__pb2.ModelVersionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/com.waterquality.proto.WaterQualityEdgeService/HealthCheck',
                request_serializer=water__quality__message__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=water__quality__message__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class WaterQualityEdgeServiceServicer(object):
    """============================================================
    gRPC Service Definition
    ============================================================

    """

    def StreamAnalysisResults(self, request_iterator, context):
        """双向流: 边缘端持续上报分析结果，云端下发指令/ACK
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportAlert(self, request, context):
        """高优先级告警上报 (需ACK确认)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelVersion(self, request, context):
        """模型版本检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterQualityEdgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAnalysisResults': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAnalysisResults,
                    request_deserializer=water__quality__message__pb2.WaterQualityMessage.FromString,
                    response_serializer=water__quality__message__pb2.EdgeCommand.SerializeToString,
            ),
            'ReportAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAlert,
                    request_deserializer=water__quality__message__pb2.AlertRequest.FromString,
                    response_serializer=water__quality__message__pb2.AlertResponse.SerializeToString,
            ),
            'GetModelVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelVersion,
                    request_deserializer=water__quality__message__pb2.ModelVersionRequest.FromString,
                    response_serializer=water__quality__message__pb2.ModelVersionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=water__quality__message__pb2.HealthCheckRequest.FromString,
                    response_serializer=water__quality__message__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.waterquality.proto.WaterQualityEdgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.waterquality.proto.WaterQualityEdgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WaterQualityEdgeService(object):
    """============================================================
    gRPC Service Definition
    ============================================================

    """

    @staticmethod
    def StreamAnalysisResults(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.waterquality.proto.WaterQualityEdgeService/StreamAnalysisResults',
            water__quality__message__pb2.WaterQualityMessage.SerializeToString,
            water__quality__message__pb2.EdgeCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.waterquality.proto.WaterQualityEdgeService/ReportAlert',
            water__quality__message__pb2.AlertRequest.SerializeToString,
            water__quality__message__pb2.AlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.waterquality.proto.WaterQualityEdgeService/GetModelVersion',
            water__quality__message__pb2.ModelVersionRequest.SerializeToString,
            water__quality__message__pb2.ModelVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.waterquality.proto.WaterQualityEdgeService/HealthCheck',
            water__quality__message__pb2.HealthCheckRequest.SerializeToString,
            water__quality__message__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
