// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface AlertDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.AlertData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0-正常,1-轻度,2-中度,3-重度
   * </pre>
   *
   * <code>int32 alert_level = 1;</code>
   * @return The alertLevel.
   */
  int getAlertLevel();

  /**
   * <pre>
   * 融合分数
   * </pre>
   *
   * <code>float final_score = 2;</code>
   * @return The finalScore.
   */
  float getFinalScore();

  /**
   * <pre>
   * 置信度
   * </pre>
   *
   * <code>float confidence = 3;</code>
   * @return The confidence.
   */
  float getConfidence();

  /**
   * <pre>
   * 告警描述
   * </pre>
   *
   * <code>string alert_message = 4;</code>
   * @return The alertMessage.
   */
  java.lang.String getAlertMessage();
  /**
   * <pre>
   * 告警描述
   * </pre>
   *
   * <code>string alert_message = 4;</code>
   * @return The bytes for alertMessage.
   */
  com.google.protobuf.ByteString
      getAlertMessageBytes();
}
