// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

/**
 * <pre>
 * ReportAlert
 * </pre>
 *
 * Protobuf type {@code com.waterquality.proto.AlertRequest}
 */
public final class AlertRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.waterquality.proto.AlertRequest)
    AlertRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AlertRequest.newBuilder() to construct.
  private AlertRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AlertRequest() {
    pointId_ = "";
    deviceId_ = "";
    alertType_ = "";
    alertMessage_ = "";
    timestampIso8601_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AlertRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.waterquality.proto.AlertRequest.class, com.waterquality.proto.AlertRequest.Builder.class);
  }

  public static final int POINT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pointId_ = "";
  /**
   * <code>string point_id = 1;</code>
   * @return The pointId.
   */
  @java.lang.Override
  public java.lang.String getPointId() {
    java.lang.Object ref = pointId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pointId_ = s;
      return s;
    }
  }
  /**
   * <code>string point_id = 1;</code>
   * @return The bytes for pointId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPointIdBytes() {
    java.lang.Object ref = pointId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pointId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceId_ = "";
  /**
   * <code>string device_id = 2;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string device_id = 2;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALERT_LEVEL_FIELD_NUMBER = 3;
  private int alertLevel_ = 0;
  /**
   * <code>int32 alert_level = 3;</code>
   * @return The alertLevel.
   */
  @java.lang.Override
  public int getAlertLevel() {
    return alertLevel_;
  }

  public static final int ALERT_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alertType_ = "";
  /**
   * <code>string alert_type = 4;</code>
   * @return The alertType.
   */
  @java.lang.Override
  public java.lang.String getAlertType() {
    java.lang.Object ref = alertType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alertType_ = s;
      return s;
    }
  }
  /**
   * <code>string alert_type = 4;</code>
   * @return The bytes for alertType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlertTypeBytes() {
    java.lang.Object ref = alertType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alertType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FINAL_SCORE_FIELD_NUMBER = 5;
  private float finalScore_ = 0F;
  /**
   * <code>float final_score = 5;</code>
   * @return The finalScore.
   */
  @java.lang.Override
  public float getFinalScore() {
    return finalScore_;
  }

  public static final int CONFIDENCE_FIELD_NUMBER = 6;
  private float confidence_ = 0F;
  /**
   * <code>float confidence = 6;</code>
   * @return The confidence.
   */
  @java.lang.Override
  public float getConfidence() {
    return confidence_;
  }

  public static final int ALERT_MESSAGE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alertMessage_ = "";
  /**
   * <code>string alert_message = 7;</code>
   * @return The alertMessage.
   */
  @java.lang.Override
  public java.lang.String getAlertMessage() {
    java.lang.Object ref = alertMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alertMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string alert_message = 7;</code>
   * @return The bytes for alertMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlertMessageBytes() {
    java.lang.Object ref = alertMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alertMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_ISO8601_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timestampIso8601_ = "";
  /**
   * <code>string timestamp_iso8601 = 8;</code>
   * @return The timestampIso8601.
   */
  @java.lang.Override
  public java.lang.String getTimestampIso8601() {
    java.lang.Object ref = timestampIso8601_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestampIso8601_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp_iso8601 = 8;</code>
   * @return The bytes for timestampIso8601.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampIso8601Bytes() {
    java.lang.Object ref = timestampIso8601_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestampIso8601_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pointId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pointId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
    }
    if (alertLevel_ != 0) {
      output.writeInt32(3, alertLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alertType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, alertType_);
    }
    if (java.lang.Float.floatToRawIntBits(finalScore_) != 0) {
      output.writeFloat(5, finalScore_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      output.writeFloat(6, confidence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alertMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, alertMessage_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestampIso8601_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, timestampIso8601_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pointId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pointId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
    }
    if (alertLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, alertLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alertType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, alertType_);
    }
    if (java.lang.Float.floatToRawIntBits(finalScore_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, finalScore_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, confidence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alertMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, alertMessage_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestampIso8601_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, timestampIso8601_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.waterquality.proto.AlertRequest)) {
      return super.equals(obj);
    }
    com.waterquality.proto.AlertRequest other = (com.waterquality.proto.AlertRequest) obj;

    if (!getPointId()
        .equals(other.getPointId())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (getAlertLevel()
        != other.getAlertLevel()) return false;
    if (!getAlertType()
        .equals(other.getAlertType())) return false;
    if (java.lang.Float.floatToIntBits(getFinalScore())
        != java.lang.Float.floatToIntBits(
            other.getFinalScore())) return false;
    if (java.lang.Float.floatToIntBits(getConfidence())
        != java.lang.Float.floatToIntBits(
            other.getConfidence())) return false;
    if (!getAlertMessage()
        .equals(other.getAlertMessage())) return false;
    if (!getTimestampIso8601()
        .equals(other.getTimestampIso8601())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POINT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPointId().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + ALERT_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getAlertLevel();
    hash = (37 * hash) + ALERT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAlertType().hashCode();
    hash = (37 * hash) + FINAL_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFinalScore());
    hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getConfidence());
    hash = (37 * hash) + ALERT_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getAlertMessage().hashCode();
    hash = (37 * hash) + TIMESTAMP_ISO8601_FIELD_NUMBER;
    hash = (53 * hash) + getTimestampIso8601().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.waterquality.proto.AlertRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.AlertRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.AlertRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.AlertRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.waterquality.proto.AlertRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ReportAlert
   * </pre>
   *
   * Protobuf type {@code com.waterquality.proto.AlertRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.waterquality.proto.AlertRequest)
      com.waterquality.proto.AlertRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waterquality.proto.AlertRequest.class, com.waterquality.proto.AlertRequest.Builder.class);
    }

    // Construct using com.waterquality.proto.AlertRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pointId_ = "";
      deviceId_ = "";
      alertLevel_ = 0;
      alertType_ = "";
      finalScore_ = 0F;
      confidence_ = 0F;
      alertMessage_ = "";
      timestampIso8601_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertRequest_descriptor;
    }

    @java.lang.Override
    public com.waterquality.proto.AlertRequest getDefaultInstanceForType() {
      return com.waterquality.proto.AlertRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.waterquality.proto.AlertRequest build() {
      com.waterquality.proto.AlertRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.waterquality.proto.AlertRequest buildPartial() {
      com.waterquality.proto.AlertRequest result = new com.waterquality.proto.AlertRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.waterquality.proto.AlertRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pointId_ = pointId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.deviceId_ = deviceId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.alertLevel_ = alertLevel_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.alertType_ = alertType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.finalScore_ = finalScore_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.confidence_ = confidence_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.alertMessage_ = alertMessage_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.timestampIso8601_ = timestampIso8601_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.waterquality.proto.AlertRequest) {
        return mergeFrom((com.waterquality.proto.AlertRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.waterquality.proto.AlertRequest other) {
      if (other == com.waterquality.proto.AlertRequest.getDefaultInstance()) return this;
      if (!other.getPointId().isEmpty()) {
        pointId_ = other.pointId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAlertLevel() != 0) {
        setAlertLevel(other.getAlertLevel());
      }
      if (!other.getAlertType().isEmpty()) {
        alertType_ = other.alertType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getFinalScore() != 0F) {
        setFinalScore(other.getFinalScore());
      }
      if (other.getConfidence() != 0F) {
        setConfidence(other.getConfidence());
      }
      if (!other.getAlertMessage().isEmpty()) {
        alertMessage_ = other.alertMessage_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getTimestampIso8601().isEmpty()) {
        timestampIso8601_ = other.timestampIso8601_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pointId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              deviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              alertLevel_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              alertType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 45: {
              finalScore_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            case 53: {
              confidence_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 58: {
              alertMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              timestampIso8601_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object pointId_ = "";
    /**
     * <code>string point_id = 1;</code>
     * @return The pointId.
     */
    public java.lang.String getPointId() {
      java.lang.Object ref = pointId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pointId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string point_id = 1;</code>
     * @return The bytes for pointId.
     */
    public com.google.protobuf.ByteString
        getPointIdBytes() {
      java.lang.Object ref = pointId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pointId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string point_id = 1;</code>
     * @param value The pointId to set.
     * @return This builder for chaining.
     */
    public Builder setPointId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pointId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string point_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPointId() {
      pointId_ = getDefaultInstance().getPointId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string point_id = 1;</code>
     * @param value The bytes for pointId to set.
     * @return This builder for chaining.
     */
    public Builder setPointIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pointId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string device_id = 2;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string device_id = 2;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string device_id = 2;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      deviceId_ = getDefaultInstance().getDeviceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 2;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int alertLevel_ ;
    /**
     * <code>int32 alert_level = 3;</code>
     * @return The alertLevel.
     */
    @java.lang.Override
    public int getAlertLevel() {
      return alertLevel_;
    }
    /**
     * <code>int32 alert_level = 3;</code>
     * @param value The alertLevel to set.
     * @return This builder for chaining.
     */
    public Builder setAlertLevel(int value) {
      
      alertLevel_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 alert_level = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertLevel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      alertLevel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object alertType_ = "";
    /**
     * <code>string alert_type = 4;</code>
     * @return The alertType.
     */
    public java.lang.String getAlertType() {
      java.lang.Object ref = alertType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alert_type = 4;</code>
     * @return The bytes for alertType.
     */
    public com.google.protobuf.ByteString
        getAlertTypeBytes() {
      java.lang.Object ref = alertType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alert_type = 4;</code>
     * @param value The alertType to set.
     * @return This builder for chaining.
     */
    public Builder setAlertType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alertType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string alert_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertType() {
      alertType_ = getDefaultInstance().getAlertType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string alert_type = 4;</code>
     * @param value The bytes for alertType to set.
     * @return This builder for chaining.
     */
    public Builder setAlertTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alertType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private float finalScore_ ;
    /**
     * <code>float final_score = 5;</code>
     * @return The finalScore.
     */
    @java.lang.Override
    public float getFinalScore() {
      return finalScore_;
    }
    /**
     * <code>float final_score = 5;</code>
     * @param value The finalScore to set.
     * @return This builder for chaining.
     */
    public Builder setFinalScore(float value) {
      
      finalScore_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>float final_score = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFinalScore() {
      bitField0_ = (bitField0_ & ~0x00000010);
      finalScore_ = 0F;
      onChanged();
      return this;
    }

    private float confidence_ ;
    /**
     * <code>float confidence = 6;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return confidence_;
    }
    /**
     * <code>float confidence = 6;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(float value) {
      
      confidence_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>float confidence = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      bitField0_ = (bitField0_ & ~0x00000020);
      confidence_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object alertMessage_ = "";
    /**
     * <code>string alert_message = 7;</code>
     * @return The alertMessage.
     */
    public java.lang.String getAlertMessage() {
      java.lang.Object ref = alertMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alert_message = 7;</code>
     * @return The bytes for alertMessage.
     */
    public com.google.protobuf.ByteString
        getAlertMessageBytes() {
      java.lang.Object ref = alertMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alert_message = 7;</code>
     * @param value The alertMessage to set.
     * @return This builder for chaining.
     */
    public Builder setAlertMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alertMessage_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string alert_message = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertMessage() {
      alertMessage_ = getDefaultInstance().getAlertMessage();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string alert_message = 7;</code>
     * @param value The bytes for alertMessage to set.
     * @return This builder for chaining.
     */
    public Builder setAlertMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alertMessage_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object timestampIso8601_ = "";
    /**
     * <code>string timestamp_iso8601 = 8;</code>
     * @return The timestampIso8601.
     */
    public java.lang.String getTimestampIso8601() {
      java.lang.Object ref = timestampIso8601_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestampIso8601_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp_iso8601 = 8;</code>
     * @return The bytes for timestampIso8601.
     */
    public com.google.protobuf.ByteString
        getTimestampIso8601Bytes() {
      java.lang.Object ref = timestampIso8601_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestampIso8601_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp_iso8601 = 8;</code>
     * @param value The timestampIso8601 to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampIso8601(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timestampIso8601_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp_iso8601 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampIso8601() {
      timestampIso8601_ = getDefaultInstance().getTimestampIso8601();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp_iso8601 = 8;</code>
     * @param value The bytes for timestampIso8601 to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampIso8601Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timestampIso8601_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.waterquality.proto.AlertRequest)
  }

  // @@protoc_insertion_point(class_scope:com.waterquality.proto.AlertRequest)
  private static final com.waterquality.proto.AlertRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.waterquality.proto.AlertRequest();
  }

  public static com.waterquality.proto.AlertRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlertRequest>
      PARSER = new com.google.protobuf.AbstractParser<AlertRequest>() {
    @java.lang.Override
    public AlertRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AlertRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlertRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.waterquality.proto.AlertRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

