// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface AlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.AlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string point_id = 1;</code>
   * @return The pointId.
   */
  java.lang.String getPointId();
  /**
   * <code>string point_id = 1;</code>
   * @return The bytes for pointId.
   */
  com.google.protobuf.ByteString
      getPointIdBytes();

  /**
   * <code>string device_id = 2;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 2;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>int32 alert_level = 3;</code>
   * @return The alertLevel.
   */
  int getAlertLevel();

  /**
   * <code>string alert_type = 4;</code>
   * @return The alertType.
   */
  java.lang.String getAlertType();
  /**
   * <code>string alert_type = 4;</code>
   * @return The bytes for alertType.
   */
  com.google.protobuf.ByteString
      getAlertTypeBytes();

  /**
   * <code>float final_score = 5;</code>
   * @return The finalScore.
   */
  float getFinalScore();

  /**
   * <code>float confidence = 6;</code>
   * @return The confidence.
   */
  float getConfidence();

  /**
   * <code>string alert_message = 7;</code>
   * @return The alertMessage.
   */
  java.lang.String getAlertMessage();
  /**
   * <code>string alert_message = 7;</code>
   * @return The bytes for alertMessage.
   */
  com.google.protobuf.ByteString
      getAlertMessageBytes();

  /**
   * <code>string timestamp_iso8601 = 8;</code>
   * @return The timestampIso8601.
   */
  java.lang.String getTimestampIso8601();
  /**
   * <code>string timestamp_iso8601 = 8;</code>
   * @return The bytes for timestampIso8601.
   */
  com.google.protobuf.ByteString
      getTimestampIso8601Bytes();
}
