// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

/**
 * <pre>
 * 告警数据
 * </pre>
 *
 * Protobuf type {@code com.waterquality.proto.AlertData}
 */
public final class AlertData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.waterquality.proto.AlertData)
    AlertDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AlertData.newBuilder() to construct.
  private AlertData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AlertData() {
    alertMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AlertData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.waterquality.proto.AlertData.class, com.waterquality.proto.AlertData.Builder.class);
  }

  public static final int ALERT_LEVEL_FIELD_NUMBER = 1;
  private int alertLevel_ = 0;
  /**
   * <pre>
   * 0-正常,1-轻度,2-中度,3-重度
   * </pre>
   *
   * <code>int32 alert_level = 1;</code>
   * @return The alertLevel.
   */
  @java.lang.Override
  public int getAlertLevel() {
    return alertLevel_;
  }

  public static final int FINAL_SCORE_FIELD_NUMBER = 2;
  private float finalScore_ = 0F;
  /**
   * <pre>
   * 融合分数
   * </pre>
   *
   * <code>float final_score = 2;</code>
   * @return The finalScore.
   */
  @java.lang.Override
  public float getFinalScore() {
    return finalScore_;
  }

  public static final int CONFIDENCE_FIELD_NUMBER = 3;
  private float confidence_ = 0F;
  /**
   * <pre>
   * 置信度
   * </pre>
   *
   * <code>float confidence = 3;</code>
   * @return The confidence.
   */
  @java.lang.Override
  public float getConfidence() {
    return confidence_;
  }

  public static final int ALERT_MESSAGE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alertMessage_ = "";
  /**
   * <pre>
   * 告警描述
   * </pre>
   *
   * <code>string alert_message = 4;</code>
   * @return The alertMessage.
   */
  @java.lang.Override
  public java.lang.String getAlertMessage() {
    java.lang.Object ref = alertMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alertMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 告警描述
   * </pre>
   *
   * <code>string alert_message = 4;</code>
   * @return The bytes for alertMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlertMessageBytes() {
    java.lang.Object ref = alertMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alertMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alertLevel_ != 0) {
      output.writeInt32(1, alertLevel_);
    }
    if (java.lang.Float.floatToRawIntBits(finalScore_) != 0) {
      output.writeFloat(2, finalScore_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      output.writeFloat(3, confidence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alertMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, alertMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alertLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, alertLevel_);
    }
    if (java.lang.Float.floatToRawIntBits(finalScore_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, finalScore_);
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, confidence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alertMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, alertMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.waterquality.proto.AlertData)) {
      return super.equals(obj);
    }
    com.waterquality.proto.AlertData other = (com.waterquality.proto.AlertData) obj;

    if (getAlertLevel()
        != other.getAlertLevel()) return false;
    if (java.lang.Float.floatToIntBits(getFinalScore())
        != java.lang.Float.floatToIntBits(
            other.getFinalScore())) return false;
    if (java.lang.Float.floatToIntBits(getConfidence())
        != java.lang.Float.floatToIntBits(
            other.getConfidence())) return false;
    if (!getAlertMessage()
        .equals(other.getAlertMessage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALERT_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getAlertLevel();
    hash = (37 * hash) + FINAL_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFinalScore());
    hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getConfidence());
    hash = (37 * hash) + ALERT_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getAlertMessage().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.waterquality.proto.AlertData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.AlertData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.AlertData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.AlertData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.AlertData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.AlertData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.AlertData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.AlertData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.AlertData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.AlertData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.AlertData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.AlertData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.waterquality.proto.AlertData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 告警数据
   * </pre>
   *
   * Protobuf type {@code com.waterquality.proto.AlertData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.waterquality.proto.AlertData)
      com.waterquality.proto.AlertDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waterquality.proto.AlertData.class, com.waterquality.proto.AlertData.Builder.class);
    }

    // Construct using com.waterquality.proto.AlertData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      alertLevel_ = 0;
      finalScore_ = 0F;
      confidence_ = 0F;
      alertMessage_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_AlertData_descriptor;
    }

    @java.lang.Override
    public com.waterquality.proto.AlertData getDefaultInstanceForType() {
      return com.waterquality.proto.AlertData.getDefaultInstance();
    }

    @java.lang.Override
    public com.waterquality.proto.AlertData build() {
      com.waterquality.proto.AlertData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.waterquality.proto.AlertData buildPartial() {
      com.waterquality.proto.AlertData result = new com.waterquality.proto.AlertData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.waterquality.proto.AlertData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.alertLevel_ = alertLevel_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.finalScore_ = finalScore_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.confidence_ = confidence_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.alertMessage_ = alertMessage_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.waterquality.proto.AlertData) {
        return mergeFrom((com.waterquality.proto.AlertData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.waterquality.proto.AlertData other) {
      if (other == com.waterquality.proto.AlertData.getDefaultInstance()) return this;
      if (other.getAlertLevel() != 0) {
        setAlertLevel(other.getAlertLevel());
      }
      if (other.getFinalScore() != 0F) {
        setFinalScore(other.getFinalScore());
      }
      if (other.getConfidence() != 0F) {
        setConfidence(other.getConfidence());
      }
      if (!other.getAlertMessage().isEmpty()) {
        alertMessage_ = other.alertMessage_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              alertLevel_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              finalScore_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              confidence_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 34: {
              alertMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int alertLevel_ ;
    /**
     * <pre>
     * 0-正常,1-轻度,2-中度,3-重度
     * </pre>
     *
     * <code>int32 alert_level = 1;</code>
     * @return The alertLevel.
     */
    @java.lang.Override
    public int getAlertLevel() {
      return alertLevel_;
    }
    /**
     * <pre>
     * 0-正常,1-轻度,2-中度,3-重度
     * </pre>
     *
     * <code>int32 alert_level = 1;</code>
     * @param value The alertLevel to set.
     * @return This builder for chaining.
     */
    public Builder setAlertLevel(int value) {
      
      alertLevel_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0-正常,1-轻度,2-中度,3-重度
     * </pre>
     *
     * <code>int32 alert_level = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertLevel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      alertLevel_ = 0;
      onChanged();
      return this;
    }

    private float finalScore_ ;
    /**
     * <pre>
     * 融合分数
     * </pre>
     *
     * <code>float final_score = 2;</code>
     * @return The finalScore.
     */
    @java.lang.Override
    public float getFinalScore() {
      return finalScore_;
    }
    /**
     * <pre>
     * 融合分数
     * </pre>
     *
     * <code>float final_score = 2;</code>
     * @param value The finalScore to set.
     * @return This builder for chaining.
     */
    public Builder setFinalScore(float value) {
      
      finalScore_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 融合分数
     * </pre>
     *
     * <code>float final_score = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFinalScore() {
      bitField0_ = (bitField0_ & ~0x00000002);
      finalScore_ = 0F;
      onChanged();
      return this;
    }

    private float confidence_ ;
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float confidence = 3;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return confidence_;
    }
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float confidence = 3;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(float value) {
      
      confidence_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float confidence = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      bitField0_ = (bitField0_ & ~0x00000004);
      confidence_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object alertMessage_ = "";
    /**
     * <pre>
     * 告警描述
     * </pre>
     *
     * <code>string alert_message = 4;</code>
     * @return The alertMessage.
     */
    public java.lang.String getAlertMessage() {
      java.lang.Object ref = alertMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 告警描述
     * </pre>
     *
     * <code>string alert_message = 4;</code>
     * @return The bytes for alertMessage.
     */
    public com.google.protobuf.ByteString
        getAlertMessageBytes() {
      java.lang.Object ref = alertMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 告警描述
     * </pre>
     *
     * <code>string alert_message = 4;</code>
     * @param value The alertMessage to set.
     * @return This builder for chaining.
     */
    public Builder setAlertMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alertMessage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 告警描述
     * </pre>
     *
     * <code>string alert_message = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertMessage() {
      alertMessage_ = getDefaultInstance().getAlertMessage();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 告警描述
     * </pre>
     *
     * <code>string alert_message = 4;</code>
     * @param value The bytes for alertMessage to set.
     * @return This builder for chaining.
     */
    public Builder setAlertMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alertMessage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.waterquality.proto.AlertData)
  }

  // @@protoc_insertion_point(class_scope:com.waterquality.proto.AlertData)
  private static final com.waterquality.proto.AlertData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.waterquality.proto.AlertData();
  }

  public static com.waterquality.proto.AlertData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlertData>
      PARSER = new com.google.protobuf.AbstractParser<AlertData>() {
    @java.lang.Override
    public AlertData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AlertData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlertData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.waterquality.proto.AlertData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

