// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface EdgeCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.EdgeCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.waterquality.proto.EdgeCommand.CommandType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.waterquality.proto.EdgeCommand.CommandType type = 1;</code>
   * @return The type.
   */
  com.waterquality.proto.EdgeCommand.CommandType getType();

  /**
   * <code>string command_id = 2;</code>
   * @return The commandId.
   */
  java.lang.String getCommandId();
  /**
   * <code>string command_id = 2;</code>
   * @return The bytes for commandId.
   */
  com.google.protobuf.ByteString
      getCommandIdBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string payload_json = 4;</code>
   * @return The payloadJson.
   */
  java.lang.String getPayloadJson();
  /**
   * <code>string payload_json = 4;</code>
   * @return The bytes for payloadJson.
   */
  com.google.protobuf.ByteString
      getPayloadJsonBytes();

  /**
   * <code>int64 server_timestamp_ms = 5;</code>
   * @return The serverTimestampMs.
   */
  long getServerTimestampMs();
}
