// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>float cpu_usage_percent = 2;</code>
   * @return The cpuUsagePercent.
   */
  float getCpuUsagePercent();

  /**
   * <code>float memory_usage_percent = 3;</code>
   * @return The memoryUsagePercent.
   */
  float getMemoryUsagePercent();

  /**
   * <code>float storage_usage_percent = 4;</code>
   * @return The storageUsagePercent.
   */
  float getStorageUsagePercent();

  /**
   * <code>int32 uptime_seconds = 5;</code>
   * @return The uptimeSeconds.
   */
  int getUptimeSeconds();

  /**
   * <code>int32 cache_queue_length = 6;</code>
   * @return The cacheQueueLength.
   */
  int getCacheQueueLength();

  /**
   * <code>float edge_temperature_celsius = 7;</code>
   * @return The edgeTemperatureCelsius.
   */
  float getEdgeTemperatureCelsius();
}
