// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

/**
 * <pre>
 * HealthCheck
 * </pre>
 *
 * Protobuf type {@code com.waterquality.proto.HealthCheckRequest}
 */
public final class HealthCheckRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.waterquality.proto.HealthCheckRequest)
    HealthCheckRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HealthCheckRequest.newBuilder() to construct.
  private HealthCheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HealthCheckRequest() {
    deviceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HealthCheckRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HealthCheckRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HealthCheckRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.waterquality.proto.HealthCheckRequest.class, com.waterquality.proto.HealthCheckRequest.Builder.class);
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceId_ = "";
  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CPU_USAGE_PERCENT_FIELD_NUMBER = 2;
  private float cpuUsagePercent_ = 0F;
  /**
   * <code>float cpu_usage_percent = 2;</code>
   * @return The cpuUsagePercent.
   */
  @java.lang.Override
  public float getCpuUsagePercent() {
    return cpuUsagePercent_;
  }

  public static final int MEMORY_USAGE_PERCENT_FIELD_NUMBER = 3;
  private float memoryUsagePercent_ = 0F;
  /**
   * <code>float memory_usage_percent = 3;</code>
   * @return The memoryUsagePercent.
   */
  @java.lang.Override
  public float getMemoryUsagePercent() {
    return memoryUsagePercent_;
  }

  public static final int STORAGE_USAGE_PERCENT_FIELD_NUMBER = 4;
  private float storageUsagePercent_ = 0F;
  /**
   * <code>float storage_usage_percent = 4;</code>
   * @return The storageUsagePercent.
   */
  @java.lang.Override
  public float getStorageUsagePercent() {
    return storageUsagePercent_;
  }

  public static final int UPTIME_SECONDS_FIELD_NUMBER = 5;
  private int uptimeSeconds_ = 0;
  /**
   * <code>int32 uptime_seconds = 5;</code>
   * @return The uptimeSeconds.
   */
  @java.lang.Override
  public int getUptimeSeconds() {
    return uptimeSeconds_;
  }

  public static final int CACHE_QUEUE_LENGTH_FIELD_NUMBER = 6;
  private int cacheQueueLength_ = 0;
  /**
   * <code>int32 cache_queue_length = 6;</code>
   * @return The cacheQueueLength.
   */
  @java.lang.Override
  public int getCacheQueueLength() {
    return cacheQueueLength_;
  }

  public static final int EDGE_TEMPERATURE_CELSIUS_FIELD_NUMBER = 7;
  private float edgeTemperatureCelsius_ = 0F;
  /**
   * <code>float edge_temperature_celsius = 7;</code>
   * @return The edgeTemperatureCelsius.
   */
  @java.lang.Override
  public float getEdgeTemperatureCelsius() {
    return edgeTemperatureCelsius_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
    }
    if (java.lang.Float.floatToRawIntBits(cpuUsagePercent_) != 0) {
      output.writeFloat(2, cpuUsagePercent_);
    }
    if (java.lang.Float.floatToRawIntBits(memoryUsagePercent_) != 0) {
      output.writeFloat(3, memoryUsagePercent_);
    }
    if (java.lang.Float.floatToRawIntBits(storageUsagePercent_) != 0) {
      output.writeFloat(4, storageUsagePercent_);
    }
    if (uptimeSeconds_ != 0) {
      output.writeInt32(5, uptimeSeconds_);
    }
    if (cacheQueueLength_ != 0) {
      output.writeInt32(6, cacheQueueLength_);
    }
    if (java.lang.Float.floatToRawIntBits(edgeTemperatureCelsius_) != 0) {
      output.writeFloat(7, edgeTemperatureCelsius_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
    }
    if (java.lang.Float.floatToRawIntBits(cpuUsagePercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, cpuUsagePercent_);
    }
    if (java.lang.Float.floatToRawIntBits(memoryUsagePercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, memoryUsagePercent_);
    }
    if (java.lang.Float.floatToRawIntBits(storageUsagePercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, storageUsagePercent_);
    }
    if (uptimeSeconds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, uptimeSeconds_);
    }
    if (cacheQueueLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, cacheQueueLength_);
    }
    if (java.lang.Float.floatToRawIntBits(edgeTemperatureCelsius_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, edgeTemperatureCelsius_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.waterquality.proto.HealthCheckRequest)) {
      return super.equals(obj);
    }
    com.waterquality.proto.HealthCheckRequest other = (com.waterquality.proto.HealthCheckRequest) obj;

    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (java.lang.Float.floatToIntBits(getCpuUsagePercent())
        != java.lang.Float.floatToIntBits(
            other.getCpuUsagePercent())) return false;
    if (java.lang.Float.floatToIntBits(getMemoryUsagePercent())
        != java.lang.Float.floatToIntBits(
            other.getMemoryUsagePercent())) return false;
    if (java.lang.Float.floatToIntBits(getStorageUsagePercent())
        != java.lang.Float.floatToIntBits(
            other.getStorageUsagePercent())) return false;
    if (getUptimeSeconds()
        != other.getUptimeSeconds()) return false;
    if (getCacheQueueLength()
        != other.getCacheQueueLength()) return false;
    if (java.lang.Float.floatToIntBits(getEdgeTemperatureCelsius())
        != java.lang.Float.floatToIntBits(
            other.getEdgeTemperatureCelsius())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + CPU_USAGE_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCpuUsagePercent());
    hash = (37 * hash) + MEMORY_USAGE_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMemoryUsagePercent());
    hash = (37 * hash) + STORAGE_USAGE_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getStorageUsagePercent());
    hash = (37 * hash) + UPTIME_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getUptimeSeconds();
    hash = (37 * hash) + CACHE_QUEUE_LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getCacheQueueLength();
    hash = (37 * hash) + EDGE_TEMPERATURE_CELSIUS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getEdgeTemperatureCelsius());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.waterquality.proto.HealthCheckRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.HealthCheckRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.HealthCheckRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.HealthCheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.waterquality.proto.HealthCheckRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * HealthCheck
   * </pre>
   *
   * Protobuf type {@code com.waterquality.proto.HealthCheckRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.waterquality.proto.HealthCheckRequest)
      com.waterquality.proto.HealthCheckRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HealthCheckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HealthCheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waterquality.proto.HealthCheckRequest.class, com.waterquality.proto.HealthCheckRequest.Builder.class);
    }

    // Construct using com.waterquality.proto.HealthCheckRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      deviceId_ = "";
      cpuUsagePercent_ = 0F;
      memoryUsagePercent_ = 0F;
      storageUsagePercent_ = 0F;
      uptimeSeconds_ = 0;
      cacheQueueLength_ = 0;
      edgeTemperatureCelsius_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HealthCheckRequest_descriptor;
    }

    @java.lang.Override
    public com.waterquality.proto.HealthCheckRequest getDefaultInstanceForType() {
      return com.waterquality.proto.HealthCheckRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.waterquality.proto.HealthCheckRequest build() {
      com.waterquality.proto.HealthCheckRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.waterquality.proto.HealthCheckRequest buildPartial() {
      com.waterquality.proto.HealthCheckRequest result = new com.waterquality.proto.HealthCheckRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.waterquality.proto.HealthCheckRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.deviceId_ = deviceId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cpuUsagePercent_ = cpuUsagePercent_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.memoryUsagePercent_ = memoryUsagePercent_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.storageUsagePercent_ = storageUsagePercent_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.uptimeSeconds_ = uptimeSeconds_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.cacheQueueLength_ = cacheQueueLength_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.edgeTemperatureCelsius_ = edgeTemperatureCelsius_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.waterquality.proto.HealthCheckRequest) {
        return mergeFrom((com.waterquality.proto.HealthCheckRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.waterquality.proto.HealthCheckRequest other) {
      if (other == com.waterquality.proto.HealthCheckRequest.getDefaultInstance()) return this;
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getCpuUsagePercent() != 0F) {
        setCpuUsagePercent(other.getCpuUsagePercent());
      }
      if (other.getMemoryUsagePercent() != 0F) {
        setMemoryUsagePercent(other.getMemoryUsagePercent());
      }
      if (other.getStorageUsagePercent() != 0F) {
        setStorageUsagePercent(other.getStorageUsagePercent());
      }
      if (other.getUptimeSeconds() != 0) {
        setUptimeSeconds(other.getUptimeSeconds());
      }
      if (other.getCacheQueueLength() != 0) {
        setCacheQueueLength(other.getCacheQueueLength());
      }
      if (other.getEdgeTemperatureCelsius() != 0F) {
        setEdgeTemperatureCelsius(other.getEdgeTemperatureCelsius());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              deviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              cpuUsagePercent_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              memoryUsagePercent_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              storageUsagePercent_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 40: {
              uptimeSeconds_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              cacheQueueLength_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 61: {
              edgeTemperatureCelsius_ = input.readFloat();
              bitField0_ |= 0x00000040;
              break;
            } // case 61
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      deviceId_ = getDefaultInstance().getDeviceId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 1;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private float cpuUsagePercent_ ;
    /**
     * <code>float cpu_usage_percent = 2;</code>
     * @return The cpuUsagePercent.
     */
    @java.lang.Override
    public float getCpuUsagePercent() {
      return cpuUsagePercent_;
    }
    /**
     * <code>float cpu_usage_percent = 2;</code>
     * @param value The cpuUsagePercent to set.
     * @return This builder for chaining.
     */
    public Builder setCpuUsagePercent(float value) {
      
      cpuUsagePercent_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float cpu_usage_percent = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuUsagePercent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cpuUsagePercent_ = 0F;
      onChanged();
      return this;
    }

    private float memoryUsagePercent_ ;
    /**
     * <code>float memory_usage_percent = 3;</code>
     * @return The memoryUsagePercent.
     */
    @java.lang.Override
    public float getMemoryUsagePercent() {
      return memoryUsagePercent_;
    }
    /**
     * <code>float memory_usage_percent = 3;</code>
     * @param value The memoryUsagePercent to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryUsagePercent(float value) {
      
      memoryUsagePercent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float memory_usage_percent = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryUsagePercent() {
      bitField0_ = (bitField0_ & ~0x00000004);
      memoryUsagePercent_ = 0F;
      onChanged();
      return this;
    }

    private float storageUsagePercent_ ;
    /**
     * <code>float storage_usage_percent = 4;</code>
     * @return The storageUsagePercent.
     */
    @java.lang.Override
    public float getStorageUsagePercent() {
      return storageUsagePercent_;
    }
    /**
     * <code>float storage_usage_percent = 4;</code>
     * @param value The storageUsagePercent to set.
     * @return This builder for chaining.
     */
    public Builder setStorageUsagePercent(float value) {
      
      storageUsagePercent_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float storage_usage_percent = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStorageUsagePercent() {
      bitField0_ = (bitField0_ & ~0x00000008);
      storageUsagePercent_ = 0F;
      onChanged();
      return this;
    }

    private int uptimeSeconds_ ;
    /**
     * <code>int32 uptime_seconds = 5;</code>
     * @return The uptimeSeconds.
     */
    @java.lang.Override
    public int getUptimeSeconds() {
      return uptimeSeconds_;
    }
    /**
     * <code>int32 uptime_seconds = 5;</code>
     * @param value The uptimeSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setUptimeSeconds(int value) {
      
      uptimeSeconds_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 uptime_seconds = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUptimeSeconds() {
      bitField0_ = (bitField0_ & ~0x00000010);
      uptimeSeconds_ = 0;
      onChanged();
      return this;
    }

    private int cacheQueueLength_ ;
    /**
     * <code>int32 cache_queue_length = 6;</code>
     * @return The cacheQueueLength.
     */
    @java.lang.Override
    public int getCacheQueueLength() {
      return cacheQueueLength_;
    }
    /**
     * <code>int32 cache_queue_length = 6;</code>
     * @param value The cacheQueueLength to set.
     * @return This builder for chaining.
     */
    public Builder setCacheQueueLength(int value) {
      
      cacheQueueLength_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cache_queue_length = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCacheQueueLength() {
      bitField0_ = (bitField0_ & ~0x00000020);
      cacheQueueLength_ = 0;
      onChanged();
      return this;
    }

    private float edgeTemperatureCelsius_ ;
    /**
     * <code>float edge_temperature_celsius = 7;</code>
     * @return The edgeTemperatureCelsius.
     */
    @java.lang.Override
    public float getEdgeTemperatureCelsius() {
      return edgeTemperatureCelsius_;
    }
    /**
     * <code>float edge_temperature_celsius = 7;</code>
     * @param value The edgeTemperatureCelsius to set.
     * @return This builder for chaining.
     */
    public Builder setEdgeTemperatureCelsius(float value) {
      
      edgeTemperatureCelsius_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>float edge_temperature_celsius = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEdgeTemperatureCelsius() {
      bitField0_ = (bitField0_ & ~0x00000040);
      edgeTemperatureCelsius_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.waterquality.proto.HealthCheckRequest)
  }

  // @@protoc_insertion_point(class_scope:com.waterquality.proto.HealthCheckRequest)
  private static final com.waterquality.proto.HealthCheckRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.waterquality.proto.HealthCheckRequest();
  }

  public static com.waterquality.proto.HealthCheckRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HealthCheckRequest>
      PARSER = new com.google.protobuf.AbstractParser<HealthCheckRequest>() {
    @java.lang.Override
    public HealthCheckRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HealthCheckRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HealthCheckRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.waterquality.proto.HealthCheckRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

