// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

/**
 * <pre>
 * 心跳数据
 * </pre>
 *
 * Protobuf type {@code com.waterquality.proto.HeartbeatData}
 */
public final class HeartbeatData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.waterquality.proto.HeartbeatData)
    HeartbeatDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeartbeatData.newBuilder() to construct.
  private HeartbeatData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeartbeatData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeartbeatData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HeartbeatData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HeartbeatData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.waterquality.proto.HeartbeatData.class, com.waterquality.proto.HeartbeatData.Builder.class);
  }

  public static final int CACHE_QUEUE_LENGTH_FIELD_NUMBER = 1;
  private long cacheQueueLength_ = 0L;
  /**
   * <pre>
   * 缓存队列长度
   * </pre>
   *
   * <code>int64 cache_queue_length = 1;</code>
   * @return The cacheQueueLength.
   */
  @java.lang.Override
  public long getCacheQueueLength() {
    return cacheQueueLength_;
  }

  public static final int CPU_USAGE_FIELD_NUMBER = 2;
  private float cpuUsage_ = 0F;
  /**
   * <pre>
   * CPU使用率
   * </pre>
   *
   * <code>float cpu_usage = 2;</code>
   * @return The cpuUsage.
   */
  @java.lang.Override
  public float getCpuUsage() {
    return cpuUsage_;
  }

  public static final int MEMORY_USAGE_FIELD_NUMBER = 3;
  private float memoryUsage_ = 0F;
  /**
   * <pre>
   * 内存使用率
   * </pre>
   *
   * <code>float memory_usage = 3;</code>
   * @return The memoryUsage.
   */
  @java.lang.Override
  public float getMemoryUsage() {
    return memoryUsage_;
  }

  public static final int UPTIME_SECONDS_FIELD_NUMBER = 4;
  private int uptimeSeconds_ = 0;
  /**
   * <pre>
   * 运行时长
   * </pre>
   *
   * <code>int32 uptime_seconds = 4;</code>
   * @return The uptimeSeconds.
   */
  @java.lang.Override
  public int getUptimeSeconds() {
    return uptimeSeconds_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cacheQueueLength_ != 0L) {
      output.writeInt64(1, cacheQueueLength_);
    }
    if (java.lang.Float.floatToRawIntBits(cpuUsage_) != 0) {
      output.writeFloat(2, cpuUsage_);
    }
    if (java.lang.Float.floatToRawIntBits(memoryUsage_) != 0) {
      output.writeFloat(3, memoryUsage_);
    }
    if (uptimeSeconds_ != 0) {
      output.writeInt32(4, uptimeSeconds_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cacheQueueLength_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, cacheQueueLength_);
    }
    if (java.lang.Float.floatToRawIntBits(cpuUsage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, cpuUsage_);
    }
    if (java.lang.Float.floatToRawIntBits(memoryUsage_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, memoryUsage_);
    }
    if (uptimeSeconds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, uptimeSeconds_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.waterquality.proto.HeartbeatData)) {
      return super.equals(obj);
    }
    com.waterquality.proto.HeartbeatData other = (com.waterquality.proto.HeartbeatData) obj;

    if (getCacheQueueLength()
        != other.getCacheQueueLength()) return false;
    if (java.lang.Float.floatToIntBits(getCpuUsage())
        != java.lang.Float.floatToIntBits(
            other.getCpuUsage())) return false;
    if (java.lang.Float.floatToIntBits(getMemoryUsage())
        != java.lang.Float.floatToIntBits(
            other.getMemoryUsage())) return false;
    if (getUptimeSeconds()
        != other.getUptimeSeconds()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CACHE_QUEUE_LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCacheQueueLength());
    hash = (37 * hash) + CPU_USAGE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCpuUsage());
    hash = (37 * hash) + MEMORY_USAGE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getMemoryUsage());
    hash = (37 * hash) + UPTIME_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getUptimeSeconds();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.waterquality.proto.HeartbeatData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.HeartbeatData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.HeartbeatData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.HeartbeatData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.waterquality.proto.HeartbeatData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 心跳数据
   * </pre>
   *
   * Protobuf type {@code com.waterquality.proto.HeartbeatData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.waterquality.proto.HeartbeatData)
      com.waterquality.proto.HeartbeatDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HeartbeatData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HeartbeatData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waterquality.proto.HeartbeatData.class, com.waterquality.proto.HeartbeatData.Builder.class);
    }

    // Construct using com.waterquality.proto.HeartbeatData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cacheQueueLength_ = 0L;
      cpuUsage_ = 0F;
      memoryUsage_ = 0F;
      uptimeSeconds_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_HeartbeatData_descriptor;
    }

    @java.lang.Override
    public com.waterquality.proto.HeartbeatData getDefaultInstanceForType() {
      return com.waterquality.proto.HeartbeatData.getDefaultInstance();
    }

    @java.lang.Override
    public com.waterquality.proto.HeartbeatData build() {
      com.waterquality.proto.HeartbeatData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.waterquality.proto.HeartbeatData buildPartial() {
      com.waterquality.proto.HeartbeatData result = new com.waterquality.proto.HeartbeatData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.waterquality.proto.HeartbeatData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cacheQueueLength_ = cacheQueueLength_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cpuUsage_ = cpuUsage_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.memoryUsage_ = memoryUsage_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.uptimeSeconds_ = uptimeSeconds_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.waterquality.proto.HeartbeatData) {
        return mergeFrom((com.waterquality.proto.HeartbeatData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.waterquality.proto.HeartbeatData other) {
      if (other == com.waterquality.proto.HeartbeatData.getDefaultInstance()) return this;
      if (other.getCacheQueueLength() != 0L) {
        setCacheQueueLength(other.getCacheQueueLength());
      }
      if (other.getCpuUsage() != 0F) {
        setCpuUsage(other.getCpuUsage());
      }
      if (other.getMemoryUsage() != 0F) {
        setMemoryUsage(other.getMemoryUsage());
      }
      if (other.getUptimeSeconds() != 0) {
        setUptimeSeconds(other.getUptimeSeconds());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              cacheQueueLength_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              cpuUsage_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              memoryUsage_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 32: {
              uptimeSeconds_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long cacheQueueLength_ ;
    /**
     * <pre>
     * 缓存队列长度
     * </pre>
     *
     * <code>int64 cache_queue_length = 1;</code>
     * @return The cacheQueueLength.
     */
    @java.lang.Override
    public long getCacheQueueLength() {
      return cacheQueueLength_;
    }
    /**
     * <pre>
     * 缓存队列长度
     * </pre>
     *
     * <code>int64 cache_queue_length = 1;</code>
     * @param value The cacheQueueLength to set.
     * @return This builder for chaining.
     */
    public Builder setCacheQueueLength(long value) {
      
      cacheQueueLength_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 缓存队列长度
     * </pre>
     *
     * <code>int64 cache_queue_length = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCacheQueueLength() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cacheQueueLength_ = 0L;
      onChanged();
      return this;
    }

    private float cpuUsage_ ;
    /**
     * <pre>
     * CPU使用率
     * </pre>
     *
     * <code>float cpu_usage = 2;</code>
     * @return The cpuUsage.
     */
    @java.lang.Override
    public float getCpuUsage() {
      return cpuUsage_;
    }
    /**
     * <pre>
     * CPU使用率
     * </pre>
     *
     * <code>float cpu_usage = 2;</code>
     * @param value The cpuUsage to set.
     * @return This builder for chaining.
     */
    public Builder setCpuUsage(float value) {
      
      cpuUsage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CPU使用率
     * </pre>
     *
     * <code>float cpu_usage = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuUsage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cpuUsage_ = 0F;
      onChanged();
      return this;
    }

    private float memoryUsage_ ;
    /**
     * <pre>
     * 内存使用率
     * </pre>
     *
     * <code>float memory_usage = 3;</code>
     * @return The memoryUsage.
     */
    @java.lang.Override
    public float getMemoryUsage() {
      return memoryUsage_;
    }
    /**
     * <pre>
     * 内存使用率
     * </pre>
     *
     * <code>float memory_usage = 3;</code>
     * @param value The memoryUsage to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryUsage(float value) {
      
      memoryUsage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内存使用率
     * </pre>
     *
     * <code>float memory_usage = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryUsage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      memoryUsage_ = 0F;
      onChanged();
      return this;
    }

    private int uptimeSeconds_ ;
    /**
     * <pre>
     * 运行时长
     * </pre>
     *
     * <code>int32 uptime_seconds = 4;</code>
     * @return The uptimeSeconds.
     */
    @java.lang.Override
    public int getUptimeSeconds() {
      return uptimeSeconds_;
    }
    /**
     * <pre>
     * 运行时长
     * </pre>
     *
     * <code>int32 uptime_seconds = 4;</code>
     * @param value The uptimeSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setUptimeSeconds(int value) {
      
      uptimeSeconds_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 运行时长
     * </pre>
     *
     * <code>int32 uptime_seconds = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUptimeSeconds() {
      bitField0_ = (bitField0_ & ~0x00000008);
      uptimeSeconds_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.waterquality.proto.HeartbeatData)
  }

  // @@protoc_insertion_point(class_scope:com.waterquality.proto.HeartbeatData)
  private static final com.waterquality.proto.HeartbeatData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.waterquality.proto.HeartbeatData();
  }

  public static com.waterquality.proto.HeartbeatData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartbeatData>
      PARSER = new com.google.protobuf.AbstractParser<HeartbeatData>() {
    @java.lang.Override
    public HeartbeatData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HeartbeatData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartbeatData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.waterquality.proto.HeartbeatData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

