// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface HeartbeatDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.HeartbeatData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 缓存队列长度
   * </pre>
   *
   * <code>int64 cache_queue_length = 1;</code>
   * @return The cacheQueueLength.
   */
  long getCacheQueueLength();

  /**
   * <pre>
   * CPU使用率
   * </pre>
   *
   * <code>float cpu_usage = 2;</code>
   * @return The cpuUsage.
   */
  float getCpuUsage();

  /**
   * <pre>
   * 内存使用率
   * </pre>
   *
   * <code>float memory_usage = 3;</code>
   * @return The memoryUsage.
   */
  float getMemoryUsage();

  /**
   * <pre>
   * 运行时长
   * </pre>
   *
   * <code>int32 uptime_seconds = 4;</code>
   * @return The uptimeSeconds.
   */
  int getUptimeSeconds();
}
