// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

/**
 * <pre>
 * 影像分析结果
 * </pre>
 *
 * Protobuf type {@code com.waterquality.proto.ImageAnalysis}
 */
public final class ImageAnalysis extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.waterquality.proto.ImageAnalysis)
    ImageAnalysisOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImageAnalysis.newBuilder() to construct.
  private ImageAnalysis(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImageAnalysis() {
    pollutionProbs_ = emptyFloatList();
    pollutionTypes_ = "";
    segmentationMask_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImageAnalysis();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_ImageAnalysis_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_ImageAnalysis_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.waterquality.proto.ImageAnalysis.class, com.waterquality.proto.ImageAnalysis.Builder.class);
  }

  public static final int TURBIDITY_LEVEL_FIELD_NUMBER = 1;
  private int turbidityLevel_ = 0;
  /**
   * <pre>
   * 0-清晰,1-轻度,2-中度,3-重度
   * </pre>
   *
   * <code>int32 turbidity_level = 1;</code>
   * @return The turbidityLevel.
   */
  @java.lang.Override
  public int getTurbidityLevel() {
    return turbidityLevel_;
  }

  public static final int POLLUTION_PROBS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList pollutionProbs_;
  /**
   * <pre>
   * 各类污染物概率 [浑浊,藻类,工业污染,正常]
   * </pre>
   *
   * <code>repeated float pollution_probs = 2;</code>
   * @return A list containing the pollutionProbs.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getPollutionProbsList() {
    return pollutionProbs_;
  }
  /**
   * <pre>
   * 各类污染物概率 [浑浊,藻类,工业污染,正常]
   * </pre>
   *
   * <code>repeated float pollution_probs = 2;</code>
   * @return The count of pollutionProbs.
   */
  public int getPollutionProbsCount() {
    return pollutionProbs_.size();
  }
  /**
   * <pre>
   * 各类污染物概率 [浑浊,藻类,工业污染,正常]
   * </pre>
   *
   * <code>repeated float pollution_probs = 2;</code>
   * @param index The index of the element to return.
   * @return The pollutionProbs at the given index.
   */
  public float getPollutionProbs(int index) {
    return pollutionProbs_.getFloat(index);
  }
  private int pollutionProbsMemoizedSerializedSize = -1;

  public static final int CONFIDENCE_FIELD_NUMBER = 3;
  private float confidence_ = 0F;
  /**
   * <code>float confidence = 3;</code>
   * @return The confidence.
   */
  @java.lang.Override
  public float getConfidence() {
    return confidence_;
  }

  public static final int IMAGE_SCORE_FIELD_NUMBER = 4;
  private float imageScore_ = 0F;
  /**
   * <code>float image_score = 4;</code>
   * @return The imageScore.
   */
  @java.lang.Override
  public float getImageScore() {
    return imageScore_;
  }

  public static final int POLLUTION_TYPES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pollutionTypes_ = "";
  /**
   * <pre>
   * 逗号分隔的污染类型
   * </pre>
   *
   * <code>string pollution_types = 5;</code>
   * @return The pollutionTypes.
   */
  @java.lang.Override
  public java.lang.String getPollutionTypes() {
    java.lang.Object ref = pollutionTypes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pollutionTypes_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 逗号分隔的污染类型
   * </pre>
   *
   * <code>string pollution_types = 5;</code>
   * @return The bytes for pollutionTypes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPollutionTypesBytes() {
    java.lang.Object ref = pollutionTypes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pollutionTypes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEGMENTATION_MASK_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString segmentationMask_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * U-Net分割掩码(可选)
   * </pre>
   *
   * <code>bytes segmentation_mask = 6;</code>
   * @return The segmentationMask.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSegmentationMask() {
    return segmentationMask_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (turbidityLevel_ != 0) {
      output.writeInt32(1, turbidityLevel_);
    }
    if (getPollutionProbsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(pollutionProbsMemoizedSerializedSize);
    }
    for (int i = 0; i < pollutionProbs_.size(); i++) {
      output.writeFloatNoTag(pollutionProbs_.getFloat(i));
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      output.writeFloat(3, confidence_);
    }
    if (java.lang.Float.floatToRawIntBits(imageScore_) != 0) {
      output.writeFloat(4, imageScore_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pollutionTypes_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, pollutionTypes_);
    }
    if (!segmentationMask_.isEmpty()) {
      output.writeBytes(6, segmentationMask_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (turbidityLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, turbidityLevel_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getPollutionProbsList().size();
      size += dataSize;
      if (!getPollutionProbsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      pollutionProbsMemoizedSerializedSize = dataSize;
    }
    if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, confidence_);
    }
    if (java.lang.Float.floatToRawIntBits(imageScore_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, imageScore_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pollutionTypes_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, pollutionTypes_);
    }
    if (!segmentationMask_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, segmentationMask_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.waterquality.proto.ImageAnalysis)) {
      return super.equals(obj);
    }
    com.waterquality.proto.ImageAnalysis other = (com.waterquality.proto.ImageAnalysis) obj;

    if (getTurbidityLevel()
        != other.getTurbidityLevel()) return false;
    if (!getPollutionProbsList()
        .equals(other.getPollutionProbsList())) return false;
    if (java.lang.Float.floatToIntBits(getConfidence())
        != java.lang.Float.floatToIntBits(
            other.getConfidence())) return false;
    if (java.lang.Float.floatToIntBits(getImageScore())
        != java.lang.Float.floatToIntBits(
            other.getImageScore())) return false;
    if (!getPollutionTypes()
        .equals(other.getPollutionTypes())) return false;
    if (!getSegmentationMask()
        .equals(other.getSegmentationMask())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TURBIDITY_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getTurbidityLevel();
    if (getPollutionProbsCount() > 0) {
      hash = (37 * hash) + POLLUTION_PROBS_FIELD_NUMBER;
      hash = (53 * hash) + getPollutionProbsList().hashCode();
    }
    hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getConfidence());
    hash = (37 * hash) + IMAGE_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getImageScore());
    hash = (37 * hash) + POLLUTION_TYPES_FIELD_NUMBER;
    hash = (53 * hash) + getPollutionTypes().hashCode();
    hash = (37 * hash) + SEGMENTATION_MASK_FIELD_NUMBER;
    hash = (53 * hash) + getSegmentationMask().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.waterquality.proto.ImageAnalysis parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.ImageAnalysis parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.ImageAnalysis parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.ImageAnalysis parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.waterquality.proto.ImageAnalysis prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 影像分析结果
   * </pre>
   *
   * Protobuf type {@code com.waterquality.proto.ImageAnalysis}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.waterquality.proto.ImageAnalysis)
      com.waterquality.proto.ImageAnalysisOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_ImageAnalysis_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_ImageAnalysis_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waterquality.proto.ImageAnalysis.class, com.waterquality.proto.ImageAnalysis.Builder.class);
    }

    // Construct using com.waterquality.proto.ImageAnalysis.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      turbidityLevel_ = 0;
      pollutionProbs_ = emptyFloatList();
      confidence_ = 0F;
      imageScore_ = 0F;
      pollutionTypes_ = "";
      segmentationMask_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_ImageAnalysis_descriptor;
    }

    @java.lang.Override
    public com.waterquality.proto.ImageAnalysis getDefaultInstanceForType() {
      return com.waterquality.proto.ImageAnalysis.getDefaultInstance();
    }

    @java.lang.Override
    public com.waterquality.proto.ImageAnalysis build() {
      com.waterquality.proto.ImageAnalysis result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.waterquality.proto.ImageAnalysis buildPartial() {
      com.waterquality.proto.ImageAnalysis result = new com.waterquality.proto.ImageAnalysis(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.waterquality.proto.ImageAnalysis result) {
      if (((bitField0_ & 0x00000002) != 0)) {
        pollutionProbs_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.pollutionProbs_ = pollutionProbs_;
    }

    private void buildPartial0(com.waterquality.proto.ImageAnalysis result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.turbidityLevel_ = turbidityLevel_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.confidence_ = confidence_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.imageScore_ = imageScore_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.pollutionTypes_ = pollutionTypes_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.segmentationMask_ = segmentationMask_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.waterquality.proto.ImageAnalysis) {
        return mergeFrom((com.waterquality.proto.ImageAnalysis)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.waterquality.proto.ImageAnalysis other) {
      if (other == com.waterquality.proto.ImageAnalysis.getDefaultInstance()) return this;
      if (other.getTurbidityLevel() != 0) {
        setTurbidityLevel(other.getTurbidityLevel());
      }
      if (!other.pollutionProbs_.isEmpty()) {
        if (pollutionProbs_.isEmpty()) {
          pollutionProbs_ = other.pollutionProbs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensurePollutionProbsIsMutable();
          pollutionProbs_.addAll(other.pollutionProbs_);
        }
        onChanged();
      }
      if (other.getConfidence() != 0F) {
        setConfidence(other.getConfidence());
      }
      if (other.getImageScore() != 0F) {
        setImageScore(other.getImageScore());
      }
      if (!other.getPollutionTypes().isEmpty()) {
        pollutionTypes_ = other.pollutionTypes_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getSegmentationMask() != com.google.protobuf.ByteString.EMPTY) {
        setSegmentationMask(other.getSegmentationMask());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              turbidityLevel_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              float v = input.readFloat();
              ensurePollutionProbsIsMutable();
              pollutionProbs_.addFloat(v);
              break;
            } // case 21
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensurePollutionProbsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                pollutionProbs_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 29: {
              confidence_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              imageScore_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 42: {
              pollutionTypes_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              segmentationMask_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int turbidityLevel_ ;
    /**
     * <pre>
     * 0-清晰,1-轻度,2-中度,3-重度
     * </pre>
     *
     * <code>int32 turbidity_level = 1;</code>
     * @return The turbidityLevel.
     */
    @java.lang.Override
    public int getTurbidityLevel() {
      return turbidityLevel_;
    }
    /**
     * <pre>
     * 0-清晰,1-轻度,2-中度,3-重度
     * </pre>
     *
     * <code>int32 turbidity_level = 1;</code>
     * @param value The turbidityLevel to set.
     * @return This builder for chaining.
     */
    public Builder setTurbidityLevel(int value) {
      
      turbidityLevel_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0-清晰,1-轻度,2-中度,3-重度
     * </pre>
     *
     * <code>int32 turbidity_level = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTurbidityLevel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      turbidityLevel_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList pollutionProbs_ = emptyFloatList();
    private void ensurePollutionProbsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        pollutionProbs_ = mutableCopy(pollutionProbs_);
        bitField0_ |= 0x00000002;
      }
    }
    /**
     * <pre>
     * 各类污染物概率 [浑浊,藻类,工业污染,正常]
     * </pre>
     *
     * <code>repeated float pollution_probs = 2;</code>
     * @return A list containing the pollutionProbs.
     */
    public java.util.List<java.lang.Float>
        getPollutionProbsList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(pollutionProbs_) : pollutionProbs_;
    }
    /**
     * <pre>
     * 各类污染物概率 [浑浊,藻类,工业污染,正常]
     * </pre>
     *
     * <code>repeated float pollution_probs = 2;</code>
     * @return The count of pollutionProbs.
     */
    public int getPollutionProbsCount() {
      return pollutionProbs_.size();
    }
    /**
     * <pre>
     * 各类污染物概率 [浑浊,藻类,工业污染,正常]
     * </pre>
     *
     * <code>repeated float pollution_probs = 2;</code>
     * @param index The index of the element to return.
     * @return The pollutionProbs at the given index.
     */
    public float getPollutionProbs(int index) {
      return pollutionProbs_.getFloat(index);
    }
    /**
     * <pre>
     * 各类污染物概率 [浑浊,藻类,工业污染,正常]
     * </pre>
     *
     * <code>repeated float pollution_probs = 2;</code>
     * @param index The index to set the value at.
     * @param value The pollutionProbs to set.
     * @return This builder for chaining.
     */
    public Builder setPollutionProbs(
        int index, float value) {
      
      ensurePollutionProbsIsMutable();
      pollutionProbs_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 各类污染物概率 [浑浊,藻类,工业污染,正常]
     * </pre>
     *
     * <code>repeated float pollution_probs = 2;</code>
     * @param value The pollutionProbs to add.
     * @return This builder for chaining.
     */
    public Builder addPollutionProbs(float value) {
      
      ensurePollutionProbsIsMutable();
      pollutionProbs_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 各类污染物概率 [浑浊,藻类,工业污染,正常]
     * </pre>
     *
     * <code>repeated float pollution_probs = 2;</code>
     * @param values The pollutionProbs to add.
     * @return This builder for chaining.
     */
    public Builder addAllPollutionProbs(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensurePollutionProbsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, pollutionProbs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 各类污染物概率 [浑浊,藻类,工业污染,正常]
     * </pre>
     *
     * <code>repeated float pollution_probs = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPollutionProbs() {
      pollutionProbs_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private float confidence_ ;
    /**
     * <code>float confidence = 3;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return confidence_;
    }
    /**
     * <code>float confidence = 3;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(float value) {
      
      confidence_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float confidence = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      bitField0_ = (bitField0_ & ~0x00000004);
      confidence_ = 0F;
      onChanged();
      return this;
    }

    private float imageScore_ ;
    /**
     * <code>float image_score = 4;</code>
     * @return The imageScore.
     */
    @java.lang.Override
    public float getImageScore() {
      return imageScore_;
    }
    /**
     * <code>float image_score = 4;</code>
     * @param value The imageScore to set.
     * @return This builder for chaining.
     */
    public Builder setImageScore(float value) {
      
      imageScore_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float image_score = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageScore() {
      bitField0_ = (bitField0_ & ~0x00000008);
      imageScore_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object pollutionTypes_ = "";
    /**
     * <pre>
     * 逗号分隔的污染类型
     * </pre>
     *
     * <code>string pollution_types = 5;</code>
     * @return The pollutionTypes.
     */
    public java.lang.String getPollutionTypes() {
      java.lang.Object ref = pollutionTypes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pollutionTypes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 逗号分隔的污染类型
     * </pre>
     *
     * <code>string pollution_types = 5;</code>
     * @return The bytes for pollutionTypes.
     */
    public com.google.protobuf.ByteString
        getPollutionTypesBytes() {
      java.lang.Object ref = pollutionTypes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pollutionTypes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 逗号分隔的污染类型
     * </pre>
     *
     * <code>string pollution_types = 5;</code>
     * @param value The pollutionTypes to set.
     * @return This builder for chaining.
     */
    public Builder setPollutionTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pollutionTypes_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 逗号分隔的污染类型
     * </pre>
     *
     * <code>string pollution_types = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPollutionTypes() {
      pollutionTypes_ = getDefaultInstance().getPollutionTypes();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 逗号分隔的污染类型
     * </pre>
     *
     * <code>string pollution_types = 5;</code>
     * @param value The bytes for pollutionTypes to set.
     * @return This builder for chaining.
     */
    public Builder setPollutionTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pollutionTypes_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString segmentationMask_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * U-Net分割掩码(可选)
     * </pre>
     *
     * <code>bytes segmentation_mask = 6;</code>
     * @return The segmentationMask.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSegmentationMask() {
      return segmentationMask_;
    }
    /**
     * <pre>
     * U-Net分割掩码(可选)
     * </pre>
     *
     * <code>bytes segmentation_mask = 6;</code>
     * @param value The segmentationMask to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentationMask(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      segmentationMask_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * U-Net分割掩码(可选)
     * </pre>
     *
     * <code>bytes segmentation_mask = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSegmentationMask() {
      bitField0_ = (bitField0_ & ~0x00000020);
      segmentationMask_ = getDefaultInstance().getSegmentationMask();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.waterquality.proto.ImageAnalysis)
  }

  // @@protoc_insertion_point(class_scope:com.waterquality.proto.ImageAnalysis)
  private static final com.waterquality.proto.ImageAnalysis DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.waterquality.proto.ImageAnalysis();
  }

  public static com.waterquality.proto.ImageAnalysis getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImageAnalysis>
      PARSER = new com.google.protobuf.AbstractParser<ImageAnalysis>() {
    @java.lang.Override
    public ImageAnalysis parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ImageAnalysis> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImageAnalysis> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.waterquality.proto.ImageAnalysis getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

