// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface ImageAnalysisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.ImageAnalysis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0-清晰,1-轻度,2-中度,3-重度
   * </pre>
   *
   * <code>int32 turbidity_level = 1;</code>
   * @return The turbidityLevel.
   */
  int getTurbidityLevel();

  /**
   * <pre>
   * 各类污染物概率 [浑浊,藻类,工业污染,正常]
   * </pre>
   *
   * <code>repeated float pollution_probs = 2;</code>
   * @return A list containing the pollutionProbs.
   */
  java.util.List<java.lang.Float> getPollutionProbsList();
  /**
   * <pre>
   * 各类污染物概率 [浑浊,藻类,工业污染,正常]
   * </pre>
   *
   * <code>repeated float pollution_probs = 2;</code>
   * @return The count of pollutionProbs.
   */
  int getPollutionProbsCount();
  /**
   * <pre>
   * 各类污染物概率 [浑浊,藻类,工业污染,正常]
   * </pre>
   *
   * <code>repeated float pollution_probs = 2;</code>
   * @param index The index of the element to return.
   * @return The pollutionProbs at the given index.
   */
  float getPollutionProbs(int index);

  /**
   * <code>float confidence = 3;</code>
   * @return The confidence.
   */
  float getConfidence();

  /**
   * <code>float image_score = 4;</code>
   * @return The imageScore.
   */
  float getImageScore();

  /**
   * <pre>
   * 逗号分隔的污染类型
   * </pre>
   *
   * <code>string pollution_types = 5;</code>
   * @return The pollutionTypes.
   */
  java.lang.String getPollutionTypes();
  /**
   * <pre>
   * 逗号分隔的污染类型
   * </pre>
   *
   * <code>string pollution_types = 5;</code>
   * @return The bytes for pollutionTypes.
   */
  com.google.protobuf.ByteString
      getPollutionTypesBytes();

  /**
   * <pre>
   * U-Net分割掩码(可选)
   * </pre>
   *
   * <code>bytes segmentation_mask = 6;</code>
   * @return The segmentationMask.
   */
  com.google.protobuf.ByteString getSegmentationMask();
}
