// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface ModelVersionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.ModelVersionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string latest_mobilenet_version = 1;</code>
   * @return The latestMobilenetVersion.
   */
  java.lang.String getLatestMobilenetVersion();
  /**
   * <code>string latest_mobilenet_version = 1;</code>
   * @return The bytes for latestMobilenetVersion.
   */
  com.google.protobuf.ByteString
      getLatestMobilenetVersionBytes();

  /**
   * <code>string latest_unet_version = 2;</code>
   * @return The latestUnetVersion.
   */
  java.lang.String getLatestUnetVersion();
  /**
   * <code>string latest_unet_version = 2;</code>
   * @return The bytes for latestUnetVersion.
   */
  com.google.protobuf.ByteString
      getLatestUnetVersionBytes();

  /**
   * <code>bool mobilenet_update_available = 3;</code>
   * @return The mobilenetUpdateAvailable.
   */
  boolean getMobilenetUpdateAvailable();

  /**
   * <code>bool unet_update_available = 4;</code>
   * @return The unetUpdateAvailable.
   */
  boolean getUnetUpdateAvailable();

  /**
   * <code>string mobilenet_download_url = 5;</code>
   * @return The mobilenetDownloadUrl.
   */
  java.lang.String getMobilenetDownloadUrl();
  /**
   * <code>string mobilenet_download_url = 5;</code>
   * @return The bytes for mobilenetDownloadUrl.
   */
  com.google.protobuf.ByteString
      getMobilenetDownloadUrlBytes();

  /**
   * <code>string unet_download_url = 6;</code>
   * @return The unetDownloadUrl.
   */
  java.lang.String getUnetDownloadUrl();
  /**
   * <code>string unet_download_url = 6;</code>
   * @return The bytes for unetDownloadUrl.
   */
  com.google.protobuf.ByteString
      getUnetDownloadUrlBytes();

  /**
   * <code>string mobilenet_checksum_sha256 = 7;</code>
   * @return The mobilenetChecksumSha256.
   */
  java.lang.String getMobilenetChecksumSha256();
  /**
   * <code>string mobilenet_checksum_sha256 = 7;</code>
   * @return The bytes for mobilenetChecksumSha256.
   */
  com.google.protobuf.ByteString
      getMobilenetChecksumSha256Bytes();

  /**
   * <code>string unet_checksum_sha256 = 8;</code>
   * @return The unetChecksumSha256.
   */
  java.lang.String getUnetChecksumSha256();
  /**
   * <code>string unet_checksum_sha256 = 8;</code>
   * @return The bytes for unetChecksumSha256.
   */
  com.google.protobuf.ByteString
      getUnetChecksumSha256Bytes();

  /**
   * <code>int64 server_timestamp_ms = 9;</code>
   * @return The serverTimestampMs.
   */
  long getServerTimestampMs();
}
