// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface ModelVersionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.ModelVersionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string current_mobilenet_version = 2;</code>
   * @return The currentMobilenetVersion.
   */
  java.lang.String getCurrentMobilenetVersion();
  /**
   * <code>string current_mobilenet_version = 2;</code>
   * @return The bytes for currentMobilenetVersion.
   */
  com.google.protobuf.ByteString
      getCurrentMobilenetVersionBytes();

  /**
   * <code>string current_unet_version = 3;</code>
   * @return The currentUnetVersion.
   */
  java.lang.String getCurrentUnetVersion();
  /**
   * <code>string current_unet_version = 3;</code>
   * @return The bytes for currentUnetVersion.
   */
  com.google.protobuf.ByteString
      getCurrentUnetVersionBytes();

  /**
   * <code>string device_type = 4;</code>
   * @return The deviceType.
   */
  java.lang.String getDeviceType();
  /**
   * <code>string device_type = 4;</code>
   * @return The bytes for deviceType.
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();
}
