// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface SensorDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.SensorData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 浊度 (NTU)
   * </pre>
   *
   * <code>float turbidity_ntu = 1;</code>
   * @return The turbidityNtu.
   */
  float getTurbidityNtu();

  /**
   * <pre>
   * COD (mg/L)
   * </pre>
   *
   * <code>float cod_value = 2;</code>
   * @return The codValue.
   */
  float getCodValue();

  /**
   * <pre>
   * pH值
   * </pre>
   *
   * <code>float ph_value = 3;</code>
   * @return The phValue.
   */
  float getPhValue();

  /**
   * <pre>
   * 水温 (摄氏度, 可选)
   * </pre>
   *
   * <code>float temperature = 4;</code>
   * @return The temperature.
   */
  float getTemperature();

  /**
   * <pre>
   * 溶解氧 (mg/L, 可选)
   * </pre>
   *
   * <code>float dissolved_oxygen = 5;</code>
   * @return The dissolvedOxygen.
   */
  float getDissolvedOxygen();
}
