// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

/**
 * <pre>
 * 传感器数据
 * </pre>
 *
 * Protobuf type {@code com.waterquality.proto.SensorData}
 */
public final class SensorData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.waterquality.proto.SensorData)
    SensorDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SensorData.newBuilder() to construct.
  private SensorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SensorData() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SensorData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_SensorData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_SensorData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.waterquality.proto.SensorData.class, com.waterquality.proto.SensorData.Builder.class);
  }

  public static final int TURBIDITY_NTU_FIELD_NUMBER = 1;
  private float turbidityNtu_ = 0F;
  /**
   * <pre>
   * 浊度 (NTU)
   * </pre>
   *
   * <code>float turbidity_ntu = 1;</code>
   * @return The turbidityNtu.
   */
  @java.lang.Override
  public float getTurbidityNtu() {
    return turbidityNtu_;
  }

  public static final int COD_VALUE_FIELD_NUMBER = 2;
  private float codValue_ = 0F;
  /**
   * <pre>
   * COD (mg/L)
   * </pre>
   *
   * <code>float cod_value = 2;</code>
   * @return The codValue.
   */
  @java.lang.Override
  public float getCodValue() {
    return codValue_;
  }

  public static final int PH_VALUE_FIELD_NUMBER = 3;
  private float phValue_ = 0F;
  /**
   * <pre>
   * pH值
   * </pre>
   *
   * <code>float ph_value = 3;</code>
   * @return The phValue.
   */
  @java.lang.Override
  public float getPhValue() {
    return phValue_;
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 4;
  private float temperature_ = 0F;
  /**
   * <pre>
   * 水温 (摄氏度, 可选)
   * </pre>
   *
   * <code>float temperature = 4;</code>
   * @return The temperature.
   */
  @java.lang.Override
  public float getTemperature() {
    return temperature_;
  }

  public static final int DISSOLVED_OXYGEN_FIELD_NUMBER = 5;
  private float dissolvedOxygen_ = 0F;
  /**
   * <pre>
   * 溶解氧 (mg/L, 可选)
   * </pre>
   *
   * <code>float dissolved_oxygen = 5;</code>
   * @return The dissolvedOxygen.
   */
  @java.lang.Override
  public float getDissolvedOxygen() {
    return dissolvedOxygen_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(turbidityNtu_) != 0) {
      output.writeFloat(1, turbidityNtu_);
    }
    if (java.lang.Float.floatToRawIntBits(codValue_) != 0) {
      output.writeFloat(2, codValue_);
    }
    if (java.lang.Float.floatToRawIntBits(phValue_) != 0) {
      output.writeFloat(3, phValue_);
    }
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      output.writeFloat(4, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(dissolvedOxygen_) != 0) {
      output.writeFloat(5, dissolvedOxygen_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(turbidityNtu_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, turbidityNtu_);
    }
    if (java.lang.Float.floatToRawIntBits(codValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, codValue_);
    }
    if (java.lang.Float.floatToRawIntBits(phValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, phValue_);
    }
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(dissolvedOxygen_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, dissolvedOxygen_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.waterquality.proto.SensorData)) {
      return super.equals(obj);
    }
    com.waterquality.proto.SensorData other = (com.waterquality.proto.SensorData) obj;

    if (java.lang.Float.floatToIntBits(getTurbidityNtu())
        != java.lang.Float.floatToIntBits(
            other.getTurbidityNtu())) return false;
    if (java.lang.Float.floatToIntBits(getCodValue())
        != java.lang.Float.floatToIntBits(
            other.getCodValue())) return false;
    if (java.lang.Float.floatToIntBits(getPhValue())
        != java.lang.Float.floatToIntBits(
            other.getPhValue())) return false;
    if (java.lang.Float.floatToIntBits(getTemperature())
        != java.lang.Float.floatToIntBits(
            other.getTemperature())) return false;
    if (java.lang.Float.floatToIntBits(getDissolvedOxygen())
        != java.lang.Float.floatToIntBits(
            other.getDissolvedOxygen())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TURBIDITY_NTU_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTurbidityNtu());
    hash = (37 * hash) + COD_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCodValue());
    hash = (37 * hash) + PH_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPhValue());
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTemperature());
    hash = (37 * hash) + DISSOLVED_OXYGEN_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDissolvedOxygen());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.waterquality.proto.SensorData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.SensorData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.SensorData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.SensorData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.SensorData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.SensorData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.SensorData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.SensorData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.SensorData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.SensorData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.SensorData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.SensorData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.waterquality.proto.SensorData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 传感器数据
   * </pre>
   *
   * Protobuf type {@code com.waterquality.proto.SensorData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.waterquality.proto.SensorData)
      com.waterquality.proto.SensorDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_SensorData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_SensorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waterquality.proto.SensorData.class, com.waterquality.proto.SensorData.Builder.class);
    }

    // Construct using com.waterquality.proto.SensorData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      turbidityNtu_ = 0F;
      codValue_ = 0F;
      phValue_ = 0F;
      temperature_ = 0F;
      dissolvedOxygen_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_SensorData_descriptor;
    }

    @java.lang.Override
    public com.waterquality.proto.SensorData getDefaultInstanceForType() {
      return com.waterquality.proto.SensorData.getDefaultInstance();
    }

    @java.lang.Override
    public com.waterquality.proto.SensorData build() {
      com.waterquality.proto.SensorData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.waterquality.proto.SensorData buildPartial() {
      com.waterquality.proto.SensorData result = new com.waterquality.proto.SensorData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.waterquality.proto.SensorData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.turbidityNtu_ = turbidityNtu_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.codValue_ = codValue_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.phValue_ = phValue_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.temperature_ = temperature_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dissolvedOxygen_ = dissolvedOxygen_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.waterquality.proto.SensorData) {
        return mergeFrom((com.waterquality.proto.SensorData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.waterquality.proto.SensorData other) {
      if (other == com.waterquality.proto.SensorData.getDefaultInstance()) return this;
      if (other.getTurbidityNtu() != 0F) {
        setTurbidityNtu(other.getTurbidityNtu());
      }
      if (other.getCodValue() != 0F) {
        setCodValue(other.getCodValue());
      }
      if (other.getPhValue() != 0F) {
        setPhValue(other.getPhValue());
      }
      if (other.getTemperature() != 0F) {
        setTemperature(other.getTemperature());
      }
      if (other.getDissolvedOxygen() != 0F) {
        setDissolvedOxygen(other.getDissolvedOxygen());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              turbidityNtu_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              codValue_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              phValue_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              temperature_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 45: {
              dissolvedOxygen_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float turbidityNtu_ ;
    /**
     * <pre>
     * 浊度 (NTU)
     * </pre>
     *
     * <code>float turbidity_ntu = 1;</code>
     * @return The turbidityNtu.
     */
    @java.lang.Override
    public float getTurbidityNtu() {
      return turbidityNtu_;
    }
    /**
     * <pre>
     * 浊度 (NTU)
     * </pre>
     *
     * <code>float turbidity_ntu = 1;</code>
     * @param value The turbidityNtu to set.
     * @return This builder for chaining.
     */
    public Builder setTurbidityNtu(float value) {
      
      turbidityNtu_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 浊度 (NTU)
     * </pre>
     *
     * <code>float turbidity_ntu = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTurbidityNtu() {
      bitField0_ = (bitField0_ & ~0x00000001);
      turbidityNtu_ = 0F;
      onChanged();
      return this;
    }

    private float codValue_ ;
    /**
     * <pre>
     * COD (mg/L)
     * </pre>
     *
     * <code>float cod_value = 2;</code>
     * @return The codValue.
     */
    @java.lang.Override
    public float getCodValue() {
      return codValue_;
    }
    /**
     * <pre>
     * COD (mg/L)
     * </pre>
     *
     * <code>float cod_value = 2;</code>
     * @param value The codValue to set.
     * @return This builder for chaining.
     */
    public Builder setCodValue(float value) {
      
      codValue_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * COD (mg/L)
     * </pre>
     *
     * <code>float cod_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      codValue_ = 0F;
      onChanged();
      return this;
    }

    private float phValue_ ;
    /**
     * <pre>
     * pH值
     * </pre>
     *
     * <code>float ph_value = 3;</code>
     * @return The phValue.
     */
    @java.lang.Override
    public float getPhValue() {
      return phValue_;
    }
    /**
     * <pre>
     * pH值
     * </pre>
     *
     * <code>float ph_value = 3;</code>
     * @param value The phValue to set.
     * @return This builder for chaining.
     */
    public Builder setPhValue(float value) {
      
      phValue_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * pH值
     * </pre>
     *
     * <code>float ph_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhValue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      phValue_ = 0F;
      onChanged();
      return this;
    }

    private float temperature_ ;
    /**
     * <pre>
     * 水温 (摄氏度, 可选)
     * </pre>
     *
     * <code>float temperature = 4;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <pre>
     * 水温 (摄氏度, 可选)
     * </pre>
     *
     * <code>float temperature = 4;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(float value) {
      
      temperature_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 水温 (摄氏度, 可选)
     * </pre>
     *
     * <code>float temperature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      bitField0_ = (bitField0_ & ~0x00000008);
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float dissolvedOxygen_ ;
    /**
     * <pre>
     * 溶解氧 (mg/L, 可选)
     * </pre>
     *
     * <code>float dissolved_oxygen = 5;</code>
     * @return The dissolvedOxygen.
     */
    @java.lang.Override
    public float getDissolvedOxygen() {
      return dissolvedOxygen_;
    }
    /**
     * <pre>
     * 溶解氧 (mg/L, 可选)
     * </pre>
     *
     * <code>float dissolved_oxygen = 5;</code>
     * @param value The dissolvedOxygen to set.
     * @return This builder for chaining.
     */
    public Builder setDissolvedOxygen(float value) {
      
      dissolvedOxygen_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 溶解氧 (mg/L, 可选)
     * </pre>
     *
     * <code>float dissolved_oxygen = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDissolvedOxygen() {
      bitField0_ = (bitField0_ & ~0x00000010);
      dissolvedOxygen_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.waterquality.proto.SensorData)
  }

  // @@protoc_insertion_point(class_scope:com.waterquality.proto.SensorData)
  private static final com.waterquality.proto.SensorData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.waterquality.proto.SensorData();
  }

  public static com.waterquality.proto.SensorData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensorData>
      PARSER = new com.google.protobuf.AbstractParser<SensorData>() {
    @java.lang.Override
    public SensorData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensorData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensorData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.waterquality.proto.SensorData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

