// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public interface WaterQualityMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.waterquality.proto.WaterQualityMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
   * @return The type.
   */
  com.waterquality.proto.WaterQualityMessage.MessageType getType();

  /**
   * <pre>
   * 监测点ID
   * </pre>
   *
   * <code>string point_id = 2;</code>
   * @return The pointId.
   */
  java.lang.String getPointId();
  /**
   * <pre>
   * 监测点ID
   * </pre>
   *
   * <code>string point_id = 2;</code>
   * @return The bytes for pointId.
   */
  com.google.protobuf.ByteString
      getPointIdBytes();

  /**
   * <pre>
   * 时间戳 (ISO-8601)
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <pre>
   * 时间戳 (ISO-8601)
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <pre>
   * 设备ID
   * </pre>
   *
   * <code>string device_id = 4;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   * 设备ID
   * </pre>
   *
   * <code>string device_id = 4;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   * 影像分析结果
   * </pre>
   *
   * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
   * @return Whether the imageAnalysis field is set.
   */
  boolean hasImageAnalysis();
  /**
   * <pre>
   * 影像分析结果
   * </pre>
   *
   * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
   * @return The imageAnalysis.
   */
  com.waterquality.proto.ImageAnalysis getImageAnalysis();
  /**
   * <pre>
   * 影像分析结果
   * </pre>
   *
   * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
   */
  com.waterquality.proto.ImageAnalysisOrBuilder getImageAnalysisOrBuilder();

  /**
   * <pre>
   * 传感器数据
   * </pre>
   *
   * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
   * @return Whether the sensorData field is set.
   */
  boolean hasSensorData();
  /**
   * <pre>
   * 传感器数据
   * </pre>
   *
   * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
   * @return The sensorData.
   */
  com.waterquality.proto.SensorData getSensorData();
  /**
   * <pre>
   * 传感器数据
   * </pre>
   *
   * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
   */
  com.waterquality.proto.SensorDataOrBuilder getSensorDataOrBuilder();

  /**
   * <pre>
   * 告警数据
   * </pre>
   *
   * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
   * @return Whether the alertData field is set.
   */
  boolean hasAlertData();
  /**
   * <pre>
   * 告警数据
   * </pre>
   *
   * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
   * @return The alertData.
   */
  com.waterquality.proto.AlertData getAlertData();
  /**
   * <pre>
   * 告警数据
   * </pre>
   *
   * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
   */
  com.waterquality.proto.AlertDataOrBuilder getAlertDataOrBuilder();

  /**
   * <pre>
   * 心跳数据
   * </pre>
   *
   * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <pre>
   * 心跳数据
   * </pre>
   *
   * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
   * @return The heartbeat.
   */
  com.waterquality.proto.HeartbeatData getHeartbeat();
  /**
   * <pre>
   * 心跳数据
   * </pre>
   *
   * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
   */
  com.waterquality.proto.HeartbeatDataOrBuilder getHeartbeatOrBuilder();
}
