// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

/**
 * <pre>
 * 边缘端上报的水质分析消息
 * </pre>
 *
 * Protobuf type {@code com.waterquality.proto.WaterQualityMessage}
 */
public final class WaterQualityMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.waterquality.proto.WaterQualityMessage)
    WaterQualityMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WaterQualityMessage.newBuilder() to construct.
  private WaterQualityMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WaterQualityMessage() {
    type_ = 0;
    pointId_ = "";
    timestamp_ = "";
    deviceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WaterQualityMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_WaterQualityMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_WaterQualityMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.waterquality.proto.WaterQualityMessage.class, com.waterquality.proto.WaterQualityMessage.Builder.class);
  }

  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * Protobuf enum {@code com.waterquality.proto.WaterQualityMessage.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>IMAGE_ANALYSIS = 1;</code>
     */
    IMAGE_ANALYSIS(1),
    /**
     * <code>SENSOR_DATA = 2;</code>
     */
    SENSOR_DATA(2),
    /**
     * <code>HEARTBEAT = 3;</code>
     */
    HEARTBEAT(3),
    /**
     * <code>ALERT = 4;</code>
     */
    ALERT(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>IMAGE_ANALYSIS = 1;</code>
     */
    public static final int IMAGE_ANALYSIS_VALUE = 1;
    /**
     * <code>SENSOR_DATA = 2;</code>
     */
    public static final int SENSOR_DATA_VALUE = 2;
    /**
     * <code>HEARTBEAT = 3;</code>
     */
    public static final int HEARTBEAT_VALUE = 3;
    /**
     * <code>ALERT = 4;</code>
     */
    public static final int ALERT_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return IMAGE_ANALYSIS;
        case 2: return SENSOR_DATA;
        case 3: return HEARTBEAT;
        case 4: return ALERT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.waterquality.proto.WaterQualityMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.waterquality.proto.WaterQualityMessage.MessageType)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.waterquality.proto.WaterQualityMessage.MessageType getType() {
    com.waterquality.proto.WaterQualityMessage.MessageType result = com.waterquality.proto.WaterQualityMessage.MessageType.forNumber(type_);
    return result == null ? com.waterquality.proto.WaterQualityMessage.MessageType.UNRECOGNIZED : result;
  }

  public static final int POINT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pointId_ = "";
  /**
   * <pre>
   * 监测点ID
   * </pre>
   *
   * <code>string point_id = 2;</code>
   * @return The pointId.
   */
  @java.lang.Override
  public java.lang.String getPointId() {
    java.lang.Object ref = pointId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pointId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 监测点ID
   * </pre>
   *
   * <code>string point_id = 2;</code>
   * @return The bytes for pointId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPointIdBytes() {
    java.lang.Object ref = pointId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pointId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timestamp_ = "";
  /**
   * <pre>
   * 时间戳 (ISO-8601)
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 时间戳 (ISO-8601)
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceId_ = "";
  /**
   * <pre>
   * 设备ID
   * </pre>
   *
   * <code>string device_id = 4;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备ID
   * </pre>
   *
   * <code>string device_id = 4;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_ANALYSIS_FIELD_NUMBER = 5;
  private com.waterquality.proto.ImageAnalysis imageAnalysis_;
  /**
   * <pre>
   * 影像分析结果
   * </pre>
   *
   * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
   * @return Whether the imageAnalysis field is set.
   */
  @java.lang.Override
  public boolean hasImageAnalysis() {
    return imageAnalysis_ != null;
  }
  /**
   * <pre>
   * 影像分析结果
   * </pre>
   *
   * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
   * @return The imageAnalysis.
   */
  @java.lang.Override
  public com.waterquality.proto.ImageAnalysis getImageAnalysis() {
    return imageAnalysis_ == null ? com.waterquality.proto.ImageAnalysis.getDefaultInstance() : imageAnalysis_;
  }
  /**
   * <pre>
   * 影像分析结果
   * </pre>
   *
   * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
   */
  @java.lang.Override
  public com.waterquality.proto.ImageAnalysisOrBuilder getImageAnalysisOrBuilder() {
    return imageAnalysis_ == null ? com.waterquality.proto.ImageAnalysis.getDefaultInstance() : imageAnalysis_;
  }

  public static final int SENSOR_DATA_FIELD_NUMBER = 6;
  private com.waterquality.proto.SensorData sensorData_;
  /**
   * <pre>
   * 传感器数据
   * </pre>
   *
   * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
   * @return Whether the sensorData field is set.
   */
  @java.lang.Override
  public boolean hasSensorData() {
    return sensorData_ != null;
  }
  /**
   * <pre>
   * 传感器数据
   * </pre>
   *
   * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
   * @return The sensorData.
   */
  @java.lang.Override
  public com.waterquality.proto.SensorData getSensorData() {
    return sensorData_ == null ? com.waterquality.proto.SensorData.getDefaultInstance() : sensorData_;
  }
  /**
   * <pre>
   * 传感器数据
   * </pre>
   *
   * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
   */
  @java.lang.Override
  public com.waterquality.proto.SensorDataOrBuilder getSensorDataOrBuilder() {
    return sensorData_ == null ? com.waterquality.proto.SensorData.getDefaultInstance() : sensorData_;
  }

  public static final int ALERT_DATA_FIELD_NUMBER = 7;
  private com.waterquality.proto.AlertData alertData_;
  /**
   * <pre>
   * 告警数据
   * </pre>
   *
   * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
   * @return Whether the alertData field is set.
   */
  @java.lang.Override
  public boolean hasAlertData() {
    return alertData_ != null;
  }
  /**
   * <pre>
   * 告警数据
   * </pre>
   *
   * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
   * @return The alertData.
   */
  @java.lang.Override
  public com.waterquality.proto.AlertData getAlertData() {
    return alertData_ == null ? com.waterquality.proto.AlertData.getDefaultInstance() : alertData_;
  }
  /**
   * <pre>
   * 告警数据
   * </pre>
   *
   * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
   */
  @java.lang.Override
  public com.waterquality.proto.AlertDataOrBuilder getAlertDataOrBuilder() {
    return alertData_ == null ? com.waterquality.proto.AlertData.getDefaultInstance() : alertData_;
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 8;
  private com.waterquality.proto.HeartbeatData heartbeat_;
  /**
   * <pre>
   * 心跳数据
   * </pre>
   *
   * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
   * @return Whether the heartbeat field is set.
   */
  @java.lang.Override
  public boolean hasHeartbeat() {
    return heartbeat_ != null;
  }
  /**
   * <pre>
   * 心跳数据
   * </pre>
   *
   * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
   * @return The heartbeat.
   */
  @java.lang.Override
  public com.waterquality.proto.HeartbeatData getHeartbeat() {
    return heartbeat_ == null ? com.waterquality.proto.HeartbeatData.getDefaultInstance() : heartbeat_;
  }
  /**
   * <pre>
   * 心跳数据
   * </pre>
   *
   * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
   */
  @java.lang.Override
  public com.waterquality.proto.HeartbeatDataOrBuilder getHeartbeatOrBuilder() {
    return heartbeat_ == null ? com.waterquality.proto.HeartbeatData.getDefaultInstance() : heartbeat_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.waterquality.proto.WaterQualityMessage.MessageType.UNKNOWN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pointId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pointId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceId_);
    }
    if (imageAnalysis_ != null) {
      output.writeMessage(5, getImageAnalysis());
    }
    if (sensorData_ != null) {
      output.writeMessage(6, getSensorData());
    }
    if (alertData_ != null) {
      output.writeMessage(7, getAlertData());
    }
    if (heartbeat_ != null) {
      output.writeMessage(8, getHeartbeat());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.waterquality.proto.WaterQualityMessage.MessageType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pointId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pointId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceId_);
    }
    if (imageAnalysis_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getImageAnalysis());
    }
    if (sensorData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getSensorData());
    }
    if (alertData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getAlertData());
    }
    if (heartbeat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getHeartbeat());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.waterquality.proto.WaterQualityMessage)) {
      return super.equals(obj);
    }
    com.waterquality.proto.WaterQualityMessage other = (com.waterquality.proto.WaterQualityMessage) obj;

    if (type_ != other.type_) return false;
    if (!getPointId()
        .equals(other.getPointId())) return false;
    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (hasImageAnalysis() != other.hasImageAnalysis()) return false;
    if (hasImageAnalysis()) {
      if (!getImageAnalysis()
          .equals(other.getImageAnalysis())) return false;
    }
    if (hasSensorData() != other.hasSensorData()) return false;
    if (hasSensorData()) {
      if (!getSensorData()
          .equals(other.getSensorData())) return false;
    }
    if (hasAlertData() != other.hasAlertData()) return false;
    if (hasAlertData()) {
      if (!getAlertData()
          .equals(other.getAlertData())) return false;
    }
    if (hasHeartbeat() != other.hasHeartbeat()) return false;
    if (hasHeartbeat()) {
      if (!getHeartbeat()
          .equals(other.getHeartbeat())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + POINT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPointId().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    if (hasImageAnalysis()) {
      hash = (37 * hash) + IMAGE_ANALYSIS_FIELD_NUMBER;
      hash = (53 * hash) + getImageAnalysis().hashCode();
    }
    if (hasSensorData()) {
      hash = (37 * hash) + SENSOR_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getSensorData().hashCode();
    }
    if (hasAlertData()) {
      hash = (37 * hash) + ALERT_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getAlertData().hashCode();
    }
    if (hasHeartbeat()) {
      hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
      hash = (53 * hash) + getHeartbeat().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.waterquality.proto.WaterQualityMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.WaterQualityMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.WaterQualityMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.waterquality.proto.WaterQualityMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.waterquality.proto.WaterQualityMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 边缘端上报的水质分析消息
   * </pre>
   *
   * Protobuf type {@code com.waterquality.proto.WaterQualityMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.waterquality.proto.WaterQualityMessage)
      com.waterquality.proto.WaterQualityMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_WaterQualityMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_WaterQualityMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.waterquality.proto.WaterQualityMessage.class, com.waterquality.proto.WaterQualityMessage.Builder.class);
    }

    // Construct using com.waterquality.proto.WaterQualityMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      pointId_ = "";
      timestamp_ = "";
      deviceId_ = "";
      imageAnalysis_ = null;
      if (imageAnalysisBuilder_ != null) {
        imageAnalysisBuilder_.dispose();
        imageAnalysisBuilder_ = null;
      }
      sensorData_ = null;
      if (sensorDataBuilder_ != null) {
        sensorDataBuilder_.dispose();
        sensorDataBuilder_ = null;
      }
      alertData_ = null;
      if (alertDataBuilder_ != null) {
        alertDataBuilder_.dispose();
        alertDataBuilder_ = null;
      }
      heartbeat_ = null;
      if (heartbeatBuilder_ != null) {
        heartbeatBuilder_.dispose();
        heartbeatBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.waterquality.proto.WaterQualityMessageOuterClass.internal_static_com_waterquality_proto_WaterQualityMessage_descriptor;
    }

    @java.lang.Override
    public com.waterquality.proto.WaterQualityMessage getDefaultInstanceForType() {
      return com.waterquality.proto.WaterQualityMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.waterquality.proto.WaterQualityMessage build() {
      com.waterquality.proto.WaterQualityMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.waterquality.proto.WaterQualityMessage buildPartial() {
      com.waterquality.proto.WaterQualityMessage result = new com.waterquality.proto.WaterQualityMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.waterquality.proto.WaterQualityMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pointId_ = pointId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.deviceId_ = deviceId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.imageAnalysis_ = imageAnalysisBuilder_ == null
            ? imageAnalysis_
            : imageAnalysisBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.sensorData_ = sensorDataBuilder_ == null
            ? sensorData_
            : sensorDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.alertData_ = alertDataBuilder_ == null
            ? alertData_
            : alertDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.heartbeat_ = heartbeatBuilder_ == null
            ? heartbeat_
            : heartbeatBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.waterquality.proto.WaterQualityMessage) {
        return mergeFrom((com.waterquality.proto.WaterQualityMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.waterquality.proto.WaterQualityMessage other) {
      if (other == com.waterquality.proto.WaterQualityMessage.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getPointId().isEmpty()) {
        pointId_ = other.pointId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasImageAnalysis()) {
        mergeImageAnalysis(other.getImageAnalysis());
      }
      if (other.hasSensorData()) {
        mergeSensorData(other.getSensorData());
      }
      if (other.hasAlertData()) {
        mergeAlertData(other.getAlertData());
      }
      if (other.hasHeartbeat()) {
        mergeHeartbeat(other.getHeartbeat());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              pointId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              timestamp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              deviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getImageAnalysisFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getSensorDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getAlertDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getHeartbeatFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.waterquality.proto.WaterQualityMessage.MessageType getType() {
      com.waterquality.proto.WaterQualityMessage.MessageType result = com.waterquality.proto.WaterQualityMessage.MessageType.forNumber(type_);
      return result == null ? com.waterquality.proto.WaterQualityMessage.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.waterquality.proto.WaterQualityMessage.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.waterquality.proto.WaterQualityMessage.MessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object pointId_ = "";
    /**
     * <pre>
     * 监测点ID
     * </pre>
     *
     * <code>string point_id = 2;</code>
     * @return The pointId.
     */
    public java.lang.String getPointId() {
      java.lang.Object ref = pointId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pointId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 监测点ID
     * </pre>
     *
     * <code>string point_id = 2;</code>
     * @return The bytes for pointId.
     */
    public com.google.protobuf.ByteString
        getPointIdBytes() {
      java.lang.Object ref = pointId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pointId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 监测点ID
     * </pre>
     *
     * <code>string point_id = 2;</code>
     * @param value The pointId to set.
     * @return This builder for chaining.
     */
    public Builder setPointId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pointId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 监测点ID
     * </pre>
     *
     * <code>string point_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPointId() {
      pointId_ = getDefaultInstance().getPointId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 监测点ID
     * </pre>
     *
     * <code>string point_id = 2;</code>
     * @param value The bytes for pointId to set.
     * @return This builder for chaining.
     */
    public Builder setPointIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pointId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <pre>
     * 时间戳 (ISO-8601)
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 时间戳 (ISO-8601)
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 时间戳 (ISO-8601)
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timestamp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳 (ISO-8601)
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      timestamp_ = getDefaultInstance().getTimestamp();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳 (ISO-8601)
     * </pre>
     *
     * <code>string timestamp = 3;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timestamp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 4;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 4;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 4;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      deviceId_ = getDefaultInstance().getDeviceId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string device_id = 4;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.waterquality.proto.ImageAnalysis imageAnalysis_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.waterquality.proto.ImageAnalysis, com.waterquality.proto.ImageAnalysis.Builder, com.waterquality.proto.ImageAnalysisOrBuilder> imageAnalysisBuilder_;
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     * @return Whether the imageAnalysis field is set.
     */
    public boolean hasImageAnalysis() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     * @return The imageAnalysis.
     */
    public com.waterquality.proto.ImageAnalysis getImageAnalysis() {
      if (imageAnalysisBuilder_ == null) {
        return imageAnalysis_ == null ? com.waterquality.proto.ImageAnalysis.getDefaultInstance() : imageAnalysis_;
      } else {
        return imageAnalysisBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     */
    public Builder setImageAnalysis(com.waterquality.proto.ImageAnalysis value) {
      if (imageAnalysisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        imageAnalysis_ = value;
      } else {
        imageAnalysisBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     */
    public Builder setImageAnalysis(
        com.waterquality.proto.ImageAnalysis.Builder builderForValue) {
      if (imageAnalysisBuilder_ == null) {
        imageAnalysis_ = builderForValue.build();
      } else {
        imageAnalysisBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     */
    public Builder mergeImageAnalysis(com.waterquality.proto.ImageAnalysis value) {
      if (imageAnalysisBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          imageAnalysis_ != null &&
          imageAnalysis_ != com.waterquality.proto.ImageAnalysis.getDefaultInstance()) {
          getImageAnalysisBuilder().mergeFrom(value);
        } else {
          imageAnalysis_ = value;
        }
      } else {
        imageAnalysisBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     */
    public Builder clearImageAnalysis() {
      bitField0_ = (bitField0_ & ~0x00000010);
      imageAnalysis_ = null;
      if (imageAnalysisBuilder_ != null) {
        imageAnalysisBuilder_.dispose();
        imageAnalysisBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     */
    public com.waterquality.proto.ImageAnalysis.Builder getImageAnalysisBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getImageAnalysisFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     */
    public com.waterquality.proto.ImageAnalysisOrBuilder getImageAnalysisOrBuilder() {
      if (imageAnalysisBuilder_ != null) {
        return imageAnalysisBuilder_.getMessageOrBuilder();
      } else {
        return imageAnalysis_ == null ?
            com.waterquality.proto.ImageAnalysis.getDefaultInstance() : imageAnalysis_;
      }
    }
    /**
     * <pre>
     * 影像分析结果
     * </pre>
     *
     * <code>.com.waterquality.proto.ImageAnalysis image_analysis = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.waterquality.proto.ImageAnalysis, com.waterquality.proto.ImageAnalysis.Builder, com.waterquality.proto.ImageAnalysisOrBuilder> 
        getImageAnalysisFieldBuilder() {
      if (imageAnalysisBuilder_ == null) {
        imageAnalysisBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.waterquality.proto.ImageAnalysis, com.waterquality.proto.ImageAnalysis.Builder, com.waterquality.proto.ImageAnalysisOrBuilder>(
                getImageAnalysis(),
                getParentForChildren(),
                isClean());
        imageAnalysis_ = null;
      }
      return imageAnalysisBuilder_;
    }

    private com.waterquality.proto.SensorData sensorData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.waterquality.proto.SensorData, com.waterquality.proto.SensorData.Builder, com.waterquality.proto.SensorDataOrBuilder> sensorDataBuilder_;
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     * @return Whether the sensorData field is set.
     */
    public boolean hasSensorData() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     * @return The sensorData.
     */
    public com.waterquality.proto.SensorData getSensorData() {
      if (sensorDataBuilder_ == null) {
        return sensorData_ == null ? com.waterquality.proto.SensorData.getDefaultInstance() : sensorData_;
      } else {
        return sensorDataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     */
    public Builder setSensorData(com.waterquality.proto.SensorData value) {
      if (sensorDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sensorData_ = value;
      } else {
        sensorDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     */
    public Builder setSensorData(
        com.waterquality.proto.SensorData.Builder builderForValue) {
      if (sensorDataBuilder_ == null) {
        sensorData_ = builderForValue.build();
      } else {
        sensorDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     */
    public Builder mergeSensorData(com.waterquality.proto.SensorData value) {
      if (sensorDataBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          sensorData_ != null &&
          sensorData_ != com.waterquality.proto.SensorData.getDefaultInstance()) {
          getSensorDataBuilder().mergeFrom(value);
        } else {
          sensorData_ = value;
        }
      } else {
        sensorDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     */
    public Builder clearSensorData() {
      bitField0_ = (bitField0_ & ~0x00000020);
      sensorData_ = null;
      if (sensorDataBuilder_ != null) {
        sensorDataBuilder_.dispose();
        sensorDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     */
    public com.waterquality.proto.SensorData.Builder getSensorDataBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getSensorDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     */
    public com.waterquality.proto.SensorDataOrBuilder getSensorDataOrBuilder() {
      if (sensorDataBuilder_ != null) {
        return sensorDataBuilder_.getMessageOrBuilder();
      } else {
        return sensorData_ == null ?
            com.waterquality.proto.SensorData.getDefaultInstance() : sensorData_;
      }
    }
    /**
     * <pre>
     * 传感器数据
     * </pre>
     *
     * <code>.com.waterquality.proto.SensorData sensor_data = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.waterquality.proto.SensorData, com.waterquality.proto.SensorData.Builder, com.waterquality.proto.SensorDataOrBuilder> 
        getSensorDataFieldBuilder() {
      if (sensorDataBuilder_ == null) {
        sensorDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.waterquality.proto.SensorData, com.waterquality.proto.SensorData.Builder, com.waterquality.proto.SensorDataOrBuilder>(
                getSensorData(),
                getParentForChildren(),
                isClean());
        sensorData_ = null;
      }
      return sensorDataBuilder_;
    }

    private com.waterquality.proto.AlertData alertData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.waterquality.proto.AlertData, com.waterquality.proto.AlertData.Builder, com.waterquality.proto.AlertDataOrBuilder> alertDataBuilder_;
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     * @return Whether the alertData field is set.
     */
    public boolean hasAlertData() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     * @return The alertData.
     */
    public com.waterquality.proto.AlertData getAlertData() {
      if (alertDataBuilder_ == null) {
        return alertData_ == null ? com.waterquality.proto.AlertData.getDefaultInstance() : alertData_;
      } else {
        return alertDataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     */
    public Builder setAlertData(com.waterquality.proto.AlertData value) {
      if (alertDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        alertData_ = value;
      } else {
        alertDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     */
    public Builder setAlertData(
        com.waterquality.proto.AlertData.Builder builderForValue) {
      if (alertDataBuilder_ == null) {
        alertData_ = builderForValue.build();
      } else {
        alertDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     */
    public Builder mergeAlertData(com.waterquality.proto.AlertData value) {
      if (alertDataBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          alertData_ != null &&
          alertData_ != com.waterquality.proto.AlertData.getDefaultInstance()) {
          getAlertDataBuilder().mergeFrom(value);
        } else {
          alertData_ = value;
        }
      } else {
        alertDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     */
    public Builder clearAlertData() {
      bitField0_ = (bitField0_ & ~0x00000040);
      alertData_ = null;
      if (alertDataBuilder_ != null) {
        alertDataBuilder_.dispose();
        alertDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     */
    public com.waterquality.proto.AlertData.Builder getAlertDataBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getAlertDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     */
    public com.waterquality.proto.AlertDataOrBuilder getAlertDataOrBuilder() {
      if (alertDataBuilder_ != null) {
        return alertDataBuilder_.getMessageOrBuilder();
      } else {
        return alertData_ == null ?
            com.waterquality.proto.AlertData.getDefaultInstance() : alertData_;
      }
    }
    /**
     * <pre>
     * 告警数据
     * </pre>
     *
     * <code>.com.waterquality.proto.AlertData alert_data = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.waterquality.proto.AlertData, com.waterquality.proto.AlertData.Builder, com.waterquality.proto.AlertDataOrBuilder> 
        getAlertDataFieldBuilder() {
      if (alertDataBuilder_ == null) {
        alertDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.waterquality.proto.AlertData, com.waterquality.proto.AlertData.Builder, com.waterquality.proto.AlertDataOrBuilder>(
                getAlertData(),
                getParentForChildren(),
                isClean());
        alertData_ = null;
      }
      return alertDataBuilder_;
    }

    private com.waterquality.proto.HeartbeatData heartbeat_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.waterquality.proto.HeartbeatData, com.waterquality.proto.HeartbeatData.Builder, com.waterquality.proto.HeartbeatDataOrBuilder> heartbeatBuilder_;
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     * @return Whether the heartbeat field is set.
     */
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     * @return The heartbeat.
     */
    public com.waterquality.proto.HeartbeatData getHeartbeat() {
      if (heartbeatBuilder_ == null) {
        return heartbeat_ == null ? com.waterquality.proto.HeartbeatData.getDefaultInstance() : heartbeat_;
      } else {
        return heartbeatBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     */
    public Builder setHeartbeat(com.waterquality.proto.HeartbeatData value) {
      if (heartbeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        heartbeat_ = value;
      } else {
        heartbeatBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     */
    public Builder setHeartbeat(
        com.waterquality.proto.HeartbeatData.Builder builderForValue) {
      if (heartbeatBuilder_ == null) {
        heartbeat_ = builderForValue.build();
      } else {
        heartbeatBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     */
    public Builder mergeHeartbeat(com.waterquality.proto.HeartbeatData value) {
      if (heartbeatBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          heartbeat_ != null &&
          heartbeat_ != com.waterquality.proto.HeartbeatData.getDefaultInstance()) {
          getHeartbeatBuilder().mergeFrom(value);
        } else {
          heartbeat_ = value;
        }
      } else {
        heartbeatBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     */
    public Builder clearHeartbeat() {
      bitField0_ = (bitField0_ & ~0x00000080);
      heartbeat_ = null;
      if (heartbeatBuilder_ != null) {
        heartbeatBuilder_.dispose();
        heartbeatBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     */
    public com.waterquality.proto.HeartbeatData.Builder getHeartbeatBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getHeartbeatFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     */
    public com.waterquality.proto.HeartbeatDataOrBuilder getHeartbeatOrBuilder() {
      if (heartbeatBuilder_ != null) {
        return heartbeatBuilder_.getMessageOrBuilder();
      } else {
        return heartbeat_ == null ?
            com.waterquality.proto.HeartbeatData.getDefaultInstance() : heartbeat_;
      }
    }
    /**
     * <pre>
     * 心跳数据
     * </pre>
     *
     * <code>.com.waterquality.proto.HeartbeatData heartbeat = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.waterquality.proto.HeartbeatData, com.waterquality.proto.HeartbeatData.Builder, com.waterquality.proto.HeartbeatDataOrBuilder> 
        getHeartbeatFieldBuilder() {
      if (heartbeatBuilder_ == null) {
        heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.waterquality.proto.HeartbeatData, com.waterquality.proto.HeartbeatData.Builder, com.waterquality.proto.HeartbeatDataOrBuilder>(
                getHeartbeat(),
                getParentForChildren(),
                isClean());
        heartbeat_ = null;
      }
      return heartbeatBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.waterquality.proto.WaterQualityMessage)
  }

  // @@protoc_insertion_point(class_scope:com.waterquality.proto.WaterQualityMessage)
  private static final com.waterquality.proto.WaterQualityMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.waterquality.proto.WaterQualityMessage();
  }

  public static com.waterquality.proto.WaterQualityMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WaterQualityMessage>
      PARSER = new com.google.protobuf.AbstractParser<WaterQualityMessage>() {
    @java.lang.Override
    public WaterQualityMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WaterQualityMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WaterQualityMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.waterquality.proto.WaterQualityMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

