// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water_quality_message.proto

package com.waterquality.proto;

public final class WaterQualityMessageOuterClass {
  private WaterQualityMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_WaterQualityMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_WaterQualityMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_ImageAnalysis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_ImageAnalysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_SensorData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_SensorData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_AlertData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_AlertData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_HeartbeatData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_HeartbeatData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_EdgeCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_EdgeCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_AlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_AlertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_AlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_AlertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_ModelVersionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_ModelVersionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_ModelVersionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_ModelVersionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_waterquality_proto_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_waterquality_proto_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033water_quality_message.proto\022\026com.water" +
      "quality.proto\"\330\003\n\023WaterQualityMessage\022E\n" +
      "\004type\030\001 \001(\01627.com.waterquality.proto.Wat" +
      "erQualityMessage.MessageType\022\020\n\010point_id" +
      "\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t\022\021\n\tdevice_id\030\004" +
      " \001(\t\022=\n\016image_analysis\030\005 \001(\0132%.com.water" +
      "quality.proto.ImageAnalysis\0227\n\013sensor_da" +
      "ta\030\006 \001(\0132\".com.waterquality.proto.Sensor" +
      "Data\0225\n\nalert_data\030\007 \001(\0132!.com.waterqual" +
      "ity.proto.AlertData\0228\n\theartbeat\030\010 \001(\0132%" +
      ".com.waterquality.proto.HeartbeatData\"Y\n" +
      "\013MessageType\022\013\n\007UNKNOWN\020\000\022\022\n\016IMAGE_ANALY" +
      "SIS\020\001\022\017\n\013SENSOR_DATA\020\002\022\r\n\tHEARTBEAT\020\003\022\t\n" +
      "\005ALERT\020\004\"\236\001\n\rImageAnalysis\022\027\n\017turbidity_" +
      "level\030\001 \001(\005\022\027\n\017pollution_probs\030\002 \003(\002\022\022\n\n" +
      "confidence\030\003 \001(\002\022\023\n\013image_score\030\004 \001(\002\022\027\n" +
      "\017pollution_types\030\005 \001(\t\022\031\n\021segmentation_m" +
      "ask\030\006 \001(\014\"w\n\nSensorData\022\025\n\rturbidity_ntu" +
      "\030\001 \001(\002\022\021\n\tcod_value\030\002 \001(\002\022\020\n\010ph_value\030\003 " +
      "\001(\002\022\023\n\013temperature\030\004 \001(\002\022\030\n\020dissolved_ox" +
      "ygen\030\005 \001(\002\"`\n\tAlertData\022\023\n\013alert_level\030\001" +
      " \001(\005\022\023\n\013final_score\030\002 \001(\002\022\022\n\nconfidence\030" +
      "\003 \001(\002\022\025\n\ralert_message\030\004 \001(\t\"l\n\rHeartbea" +
      "tData\022\032\n\022cache_queue_length\030\001 \001(\003\022\021\n\tcpu" +
      "_usage\030\002 \001(\002\022\024\n\014memory_usage\030\003 \001(\002\022\026\n\016up" +
      "time_seconds\030\004 \001(\005\"\216\002\n\013EdgeCommand\022=\n\004ty" +
      "pe\030\001 \001(\0162/.com.waterquality.proto.EdgeCo" +
      "mmand.CommandType\022\022\n\ncommand_id\030\002 \001(\t\022\017\n" +
      "\007message\030\003 \001(\t\022\024\n\014payload_json\030\004 \001(\t\022\033\n\023" +
      "server_timestamp_ms\030\005 \001(\003\"h\n\013CommandType" +
      "\022\007\n\003ACK\020\000\022\032\n\026MODEL_UPDATE_AVAILABLE\020\001\022\021\n" +
      "\rCONFIG_UPDATE\020\002\022\014\n\010SHUTDOWN\020\003\022\023\n\017RESTAR" +
      "T_CAPTURE\020\004\"\267\001\n\014AlertRequest\022\020\n\010point_id" +
      "\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t\022\023\n\013alert_level" +
      "\030\003 \001(\005\022\022\n\nalert_type\030\004 \001(\t\022\023\n\013final_scor" +
      "e\030\005 \001(\002\022\022\n\nconfidence\030\006 \001(\002\022\025\n\ralert_mes" +
      "sage\030\007 \001(\t\022\031\n\021timestamp_iso8601\030\010 \001(\t\"l\n" +
      "\rAlertResponse\022\020\n\010alert_id\030\001 \001(\t\022\016\n\006stat" +
      "us\030\002 \001(\t\022\034\n\024handling_instruction\030\003 \001(\t\022\033" +
      "\n\023server_timestamp_ms\030\004 \001(\003\"~\n\023ModelVers" +
      "ionRequest\022\021\n\tdevice_id\030\001 \001(\t\022!\n\031current" +
      "_mobilenet_version\030\002 \001(\t\022\034\n\024current_unet" +
      "_version\030\003 \001(\t\022\023\n\013device_type\030\004 \001(\t\"\261\002\n\024" +
      "ModelVersionResponse\022 \n\030latest_mobilenet" +
      "_version\030\001 \001(\t\022\033\n\023latest_unet_version\030\002 " +
      "\001(\t\022\"\n\032mobilenet_update_available\030\003 \001(\010\022" +
      "\035\n\025unet_update_available\030\004 \001(\010\022\036\n\026mobile" +
      "net_download_url\030\005 \001(\t\022\031\n\021unet_download_" +
      "url\030\006 \001(\t\022!\n\031mobilenet_checksum_sha256\030\007" +
      " \001(\t\022\034\n\024unet_checksum_sha256\030\010 \001(\t\022\033\n\023se" +
      "rver_timestamp_ms\030\t \001(\003\"\325\001\n\022HealthCheckR" +
      "equest\022\021\n\tdevice_id\030\001 \001(\t\022\031\n\021cpu_usage_p" +
      "ercent\030\002 \001(\002\022\034\n\024memory_usage_percent\030\003 \001" +
      "(\002\022\035\n\025storage_usage_percent\030\004 \001(\002\022\026\n\016upt" +
      "ime_seconds\030\005 \001(\005\022\032\n\022cache_queue_length\030" +
      "\006 \001(\005\022 \n\030edge_temperature_celsius\030\007 \001(\002\"" +
      "n\n\023HealthCheckResponse\022\016\n\006status\030\001 \001(\t\022\033" +
      "\n\023server_timestamp_ms\030\002 \001(\003\022*\n\"recommend" +
      "ed_heartbeat_interval_sec\030\003 \001(\0052\272\003\n\027Wate" +
      "rQualityEdgeService\022m\n\025StreamAnalysisRes" +
      "ults\022+.com.waterquality.proto.WaterQuali" +
      "tyMessage\032#.com.waterquality.proto.EdgeC" +
      "ommand(\0010\001\022Z\n\013ReportAlert\022$.com.waterqua" +
      "lity.proto.AlertRequest\032%.com.waterquali" +
      "ty.proto.AlertResponse\022l\n\017GetModelVersio" +
      "n\022+.com.waterquality.proto.ModelVersionR" +
      "equest\032,.com.waterquality.proto.ModelVer" +
      "sionResponse\022f\n\013HealthCheck\022*.com.waterq" +
      "uality.proto.HealthCheckRequest\032+.com.wa" +
      "terquality.proto.HealthCheckResponseB\032\n\026" +
      "com.waterquality.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_waterquality_proto_WaterQualityMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_waterquality_proto_WaterQualityMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_WaterQualityMessage_descriptor,
        new java.lang.String[] { "Type", "PointId", "Timestamp", "DeviceId", "ImageAnalysis", "SensorData", "AlertData", "Heartbeat", });
    internal_static_com_waterquality_proto_ImageAnalysis_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_waterquality_proto_ImageAnalysis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_ImageAnalysis_descriptor,
        new java.lang.String[] { "TurbidityLevel", "PollutionProbs", "Confidence", "ImageScore", "PollutionTypes", "SegmentationMask", });
    internal_static_com_waterquality_proto_SensorData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_waterquality_proto_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_SensorData_descriptor,
        new java.lang.String[] { "TurbidityNtu", "CodValue", "PhValue", "Temperature", "DissolvedOxygen", });
    internal_static_com_waterquality_proto_AlertData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_waterquality_proto_AlertData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_AlertData_descriptor,
        new java.lang.String[] { "AlertLevel", "FinalScore", "Confidence", "AlertMessage", });
    internal_static_com_waterquality_proto_HeartbeatData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_waterquality_proto_HeartbeatData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_HeartbeatData_descriptor,
        new java.lang.String[] { "CacheQueueLength", "CpuUsage", "MemoryUsage", "UptimeSeconds", });
    internal_static_com_waterquality_proto_EdgeCommand_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_waterquality_proto_EdgeCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_EdgeCommand_descriptor,
        new java.lang.String[] { "Type", "CommandId", "Message", "PayloadJson", "ServerTimestampMs", });
    internal_static_com_waterquality_proto_AlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_waterquality_proto_AlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_AlertRequest_descriptor,
        new java.lang.String[] { "PointId", "DeviceId", "AlertLevel", "AlertType", "FinalScore", "Confidence", "AlertMessage", "TimestampIso8601", });
    internal_static_com_waterquality_proto_AlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_waterquality_proto_AlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_AlertResponse_descriptor,
        new java.lang.String[] { "AlertId", "Status", "HandlingInstruction", "ServerTimestampMs", });
    internal_static_com_waterquality_proto_ModelVersionRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_waterquality_proto_ModelVersionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_ModelVersionRequest_descriptor,
        new java.lang.String[] { "DeviceId", "CurrentMobilenetVersion", "CurrentUnetVersion", "DeviceType", });
    internal_static_com_waterquality_proto_ModelVersionResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_waterquality_proto_ModelVersionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_ModelVersionResponse_descriptor,
        new java.lang.String[] { "LatestMobilenetVersion", "LatestUnetVersion", "MobilenetUpdateAvailable", "UnetUpdateAvailable", "MobilenetDownloadUrl", "UnetDownloadUrl", "MobilenetChecksumSha256", "UnetChecksumSha256", "ServerTimestampMs", });
    internal_static_com_waterquality_proto_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_waterquality_proto_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_HealthCheckRequest_descriptor,
        new java.lang.String[] { "DeviceId", "CpuUsagePercent", "MemoryUsagePercent", "StorageUsagePercent", "UptimeSeconds", "CacheQueueLength", "EdgeTemperatureCelsius", });
    internal_static_com_waterquality_proto_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_waterquality_proto_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_waterquality_proto_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", "ServerTimestampMs", "RecommendedHeartbeatIntervalSec", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
